import { industrializeProducts, type CatalogProduct, makeVariant } from '../model.js';

export const bakingPantryProducts: readonly CatalogProduct[] = industrializeProducts([
  {
    id: 1,
    slug: 'all-purpose-flour',
    name: 'All-Purpose Flour',
    description:
      'Enriched wheat flour milled from hard and soft wheat. Suitable for bread, cakes, pastry, sauces, and everyday baking with consistent results.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'all-purpose-flour',
    baseFacts: {
      texture: 'Fine soft powder',
      colour: 'White to off-white',
      source: 'Milled wheat endosperm',
      intendedUse: 'General-purpose baking and cooking flour',
      storage: 'Store in a cool dry place in an airtight container.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine soft powder',
      colour: 'White to off-white',
      source: 'Milled wheat endosperm',
      intendedUse: 'General-purpose baking and cooking flour',
      storage: 'Store in a cool dry place in an airtight container.',
      consumptionClassification: 'food',
      ingredients: ['Wheat flour', 'Niacin', 'Iron', 'Thiamine', 'Riboflavin', 'Folic acid'],
      allergens: ['Gluten (wheat)'],
      nutrition: { energy: '360 kcal', protein: '10 g', carbohydrate: '76 g', fat: '1 g' },
      servingSize: '100 g',
      dietaryAttributes: ['Vegetarian'],
    },
    tags: ['flour', 'wheat', 'baking', 'all-purpose'],
    createdAt: '2025-01-01T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-0001-001', '1 kg Bag', 1000, 295, 85, 1),
      makeVariant('BKP-0001-002', '5 kg Bag', 5000, 995, 55, 2),
      makeVariant('BKP-0001-003', '10 kg Sack', 10000, 1695, 30, 3),
    ],
  },
  {
    id: 2,
    slug: 'powdered-sugar',
    name: 'Powdered Sugar',
    description:
      'Finely ground white sugar with a small amount of cornstarch added to prevent caking. Dissolves instantly for icings, frostings, and dessert toppings.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'powdered-sugar',
    baseFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Bright white',
      source: 'Refined sugarcane or sugar beet, mechanically ground',
      intendedUse: 'Icing, frosting, dusting, and quick-dissolve sweetening',
      storage: 'Store in a cool dry place in a sealed container to prevent clumping.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Bright white',
      source: 'Refined sugarcane or sugar beet, mechanically ground',
      intendedUse: 'Icing, frosting, dusting, and quick-dissolve sweetening',
      storage: 'Store in a cool dry place in a sealed container to prevent clumping.',
      consumptionClassification: 'food',
      ingredients: ['Sugar', 'Cornstarch (anti-caking agent)'],
      allergens: [],
      nutrition: { energy: '390 kcal', protein: '0 g', carbohydrate: '99 g', fat: '0 g' },
      servingSize: '10 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['sugar', 'icing', 'confectioners', 'baking'],
    createdAt: '2025-01-02T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-0002-001', '500 g Bag', 500, 295, 60, 1),
      makeVariant('BKP-0002-002', '1 kg Bag', 1000, 495, 45, 2),
    ],
  },
  {
    id: 3,
    slug: 'cocoa-powder',
    name: 'Cocoa Powder',
    description:
      'Dutch-processed cocoa powder with a rich, smooth chocolate flavour. Ideal for brownies, cakes, hot chocolate, and confectionery with excellent colour and taste.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'cocoa-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Deep brown',
      source: 'Roasted cocoa beans, pressed and alkalised',
      intendedUse: 'Baking, hot drinks, confectionery, and dessert flavouring',
      storage: 'Store in a cool dry place. Seal tightly after opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Deep brown',
      source: 'Roasted cocoa beans, pressed and alkalised',
      intendedUse: 'Baking, hot drinks, confectionery, and dessert flavouring',
      storage: 'Store in a cool dry place. Seal tightly after opening.',
      consumptionClassification: 'food',
      ingredients: ['Cocoa powder', 'Acidity regulator (potassium carbonate)'],
      allergens: [],
      nutrition: { energy: '230 kcal', protein: '20 g', carbohydrate: '12 g', fat: '11 g' },
      servingSize: '10 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['cocoa', 'chocolate', 'baking', 'dutch-processed'],
    createdAt: '2025-01-03T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('BKP-0003-001', '250 g Bag', 250, 895, 40, 1, { compareAtPriceCents: 1095 }),
      makeVariant('BKP-0003-002', '500 g Bag', 500, 1495, 30, 2),
      makeVariant('BKP-0003-003', '1 kg Bag', 1000, 2595, 20, 3),
    ],
  },
  {
    id: 4,
    slug: 'almond-flour',
    name: 'Almond Flour',
    description:
      'Blanched and finely ground almond flour made from California almonds. Grain-free, high in protein, and perfect for macarons, cakes, and gluten-free baking.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'almond-flour',
    baseFacts: {
      texture: 'Fine meal',
      colour: 'Pale cream',
      source: 'Blanched almonds, stone-ground',
      intendedUse: 'Gluten-free baking, macarons, pastry, and breadcrumb alternative',
      storage: 'Store in a cool dry place or refrigerate after opening for extended freshness.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine meal',
      colour: 'Pale cream',
      source: 'Blanched almonds, stone-ground',
      intendedUse: 'Gluten-free baking, macarons, pastry, and breadcrumb alternative',
      storage: 'Store in a cool dry place or refrigerate after opening for extended freshness.',
      consumptionClassification: 'food',
      ingredients: ['Almonds'],
      allergens: ['Tree nuts (almonds)'],
      nutrition: { energy: '590 kcal', protein: '21 g', carbohydrate: '20 g', fat: '52 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Gluten-free', 'Grain-free', 'Vegan', 'High-protein'],
    },
    tags: ['almond', 'flour', 'gluten-free', 'baking', 'nut-flour'],
    createdAt: '2025-01-04T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('BKP-0004-001', '400 g Bag', 400, 1195, 38, 1, { compareAtPriceCents: 1495 }),
      makeVariant('BKP-0004-002', '1 kg Bag', 1000, 2495, 25, 2),
    ],
  },
  {
    id: 5,
    slug: 'baking-soda',
    name: 'Baking Soda',
    description:
      'Pure sodium bicarbonate for leavening, pH adjustment, and household use. Food-grade quality suitable for all baking applications requiring consistent rise.',
    category: 'Baking & Pantry',
    mixingGroup: null,
    consumptionClassification: 'caution',
    imageSetId: 'baking-soda',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Mined trona ore, refined to sodium bicarbonate',
      intendedUse: 'Leavening agent for baking, pH adjustment, and surface cleaning',
      storage: 'Store in a cool dry place. Replace lid tightly to maintain potency.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Mined trona ore, refined to sodium bicarbonate',
      intendedUse: 'Leavening agent for baking, pH adjustment, and surface cleaning',
      storage: 'Store in a cool dry place. Replace lid tightly to maintain potency.',
      consumptionClassification: 'caution',
      ingredients: ['Sodium bicarbonate'],
      allergens: [],
      nutrition: { energy: '0 kcal', protein: '0 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '1 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['baking', 'leavening', 'sodium-bicarbonate'],
    createdAt: '2025-01-05T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-0005-001', '200 g Tub', 200, 195, 70, 1),
      makeVariant('BKP-0005-002', '500 g Tub', 500, 395, 50, 2),
      makeVariant('BKP-0005-003', '2 kg Bag', 2000, 995, 35, 3),
    ],
  },
  {
    id: 6,
    slug: 'cornstarch',
    name: 'Cornstarch',
    description:
      'Pure corn-derived starch powder for thickening sauces, gravies, and soups. Also suitable for shortbread, batters, and anti-caking in dry blends.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'cornstarch',
    baseFacts: {
      texture: 'Silky fine powder',
      colour: 'Bright white',
      source: 'Wet-milled corn endosperm, dried',
      intendedUse: 'Thickening agent for cooking and baking, anti-caking in dry mixes',
      storage: 'Store in a cool dry place in an airtight container.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Silky fine powder',
      colour: 'Bright white',
      source: 'Wet-milled corn endosperm, dried',
      intendedUse: 'Thickening agent for cooking and baking, anti-caking in dry mixes',
      storage: 'Store in a cool dry place in an airtight container.',
      consumptionClassification: 'food',
      ingredients: ['Cornstarch'],
      allergens: [],
      nutrition: { energy: '380 kcal', protein: '0 g', carbohydrate: '94 g', fat: '0 g' },
      servingSize: '10 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['cornstarch', 'thickener', 'baking', 'gluten-free'],
    createdAt: '2025-01-06T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-0006-001', '250 g Box', 250, 195, 65, 1),
      makeVariant('BKP-0006-002', '500 g Box', 500, 295, 50, 2),
    ],
  },
  {
    id: 7,
    slug: 'bread-flour',
    name: 'Bread Flour',
    description:
      'Strong white bread flour with 12.5% protein content for excellent gluten development. Produces well-risen, chewy-crusted artisan and sandwich loaves.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'bread-flour',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'Cream white',
      source: 'Hard wheat, roller-milled',
      intendedUse: 'Yeasted bread, pizza dough, bagels, and high-gluten baked goods',
      storage: 'Store in a cool dry place. Use within 6 months of milling date.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine granular powder',
      colour: 'Cream white',
      source: 'Hard wheat, roller-milled',
      intendedUse: 'Yeasted bread, pizza dough, bagels, and high-gluten baked goods',
      storage: 'Store in a cool dry place. Use within 6 months of milling date.',
      consumptionClassification: 'food',
      ingredients: ['Wheat flour', 'Niacin', 'Iron', 'Thiamine', 'Riboflavin', 'Folic acid'],
      allergens: ['Gluten (wheat)'],
      nutrition: { energy: '355 kcal', protein: '12.5 g', carbohydrate: '72 g', fat: '1.5 g' },
      servingSize: '100 g',
      dietaryAttributes: ['Vegetarian'],
    },
    tags: ['flour', 'bread', 'wheat', 'high-protein', 'strong-flour'],
    createdAt: '2025-01-07T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('BKP-0007-001', '1.5 kg Bag', 1500, 395, 55, 1, { compareAtPriceCents: 495 }),
      makeVariant('BKP-0007-002', '5 kg Bag', 5000, 1095, 40, 2),
    ],
  },
  {
    id: 1015,
    slug: 'whole-wheat-flour',
    name: 'Whole Wheat Flour',
    description:
      'Stone-ground whole wheat flour retaining bran and germ. Nutty flavour with more fibre than white flour, ideal for rustic breads and hearty baking.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'whole-wheat-flour',
    baseFacts: {
      texture: 'Medium-coarse powder with visible bran flecks',
      colour: 'Warm brown',
      source: 'Whole wheat kernels, stone-ground',
      intendedUse: 'Wholegrain bread, muffins, pancakes, and rustic baking',
      storage: 'Store in a cool dry place. Refrigerate for best shelf life.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Medium-coarse powder with visible bran flecks',
      colour: 'Warm brown',
      source: 'Whole wheat kernels, stone-ground',
      intendedUse: 'Wholegrain bread, muffins, pancakes, and rustic baking',
      storage: 'Store in a cool dry place. Refrigerate for best shelf life.',
      consumptionClassification: 'food',
      ingredients: ['Whole wheat flour'],
      allergens: ['Gluten (wheat)'],
      nutrition: {
        energy: '340 kcal',
        protein: '13 g',
        carbohydrate: '72 g',
        fat: '2 g',
        fibre: '11 g',
      },
      servingSize: '100 g',
      dietaryAttributes: ['Vegetarian', 'High-fibre'],
    },
    tags: ['flour', 'whole-wheat', 'wholegrain', 'baking'],
    createdAt: '2025-03-06T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1015-001', '1 kg Bag', 1000, 345, 50, 1),
      makeVariant('BKP-1015-002', '5 kg Bag', 5000, 1195, 30, 2),
    ],
  },
  {
    id: 1016,
    slug: 'baking-powder',
    name: 'Baking Powder',
    description:
      'Double-acting baking powder blend of sodium bicarbonate and acid phosphates. Produces consistent lift in cakes, muffins, scones, and quick breads.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'baking-powder',
    baseFacts: {
      texture: 'Fine free-flowing powder',
      colour: 'White',
      source: 'Sodium bicarbonate, monocalcium phosphate, cornstarch',
      intendedUse: 'Chemical leavening agent for quick breads, cakes, and biscuits',
      storage: 'Store in a cool dry place. Replace lid tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine free-flowing powder',
      colour: 'White',
      source: 'Sodium bicarbonate, monocalcium phosphate, cornstarch',
      intendedUse: 'Chemical leavening agent for quick breads, cakes, and biscuits',
      storage: 'Store in a cool dry place. Replace lid tightly.',
      consumptionClassification: 'food',
      ingredients: ['Cornstarch', 'Sodium bicarbonate', 'Monocalcium phosphate'],
      allergens: [],
      nutrition: { energy: '180 kcal', protein: '0 g', carbohydrate: '45 g', fat: '0 g' },
      servingSize: '5 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['baking', 'leavening', 'rising-agent'],
    createdAt: '2025-03-07T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1016-001', '120 g Tub', 120, 195, 55, 1),
      makeVariant('BKP-1016-002', '400 g Tub', 400, 445, 35, 2),
    ],
  },
  {
    id: 1017,
    slug: 'graham-cracker-crumbs',
    name: 'Graham Cracker Crumbs',
    description:
      'Pre-ground graham cracker crumbs for cheesecake bases, pie crusts, and dessert toppings. Consistent fine texture saves time on manual crushing.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'graham-cracker-crumbs',
    baseFacts: {
      texture: 'Fine crumb',
      colour: 'Golden brown',
      source: 'Baked whole wheat graham crackers, mechanically ground',
      intendedUse: 'Cheesecake crusts, pie bases, dessert bars, and crumble toppings',
      storage: 'Store in a cool dry place. Reseal bag to maintain crispness.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine crumb',
      colour: 'Golden brown',
      source: 'Baked whole wheat graham crackers, mechanically ground',
      intendedUse: 'Cheesecake crusts, pie bases, dessert bars, and crumble toppings',
      storage: 'Store in a cool dry place. Reseal bag to maintain crispness.',
      consumptionClassification: 'food',
      ingredients: [
        'Whole wheat flour',
        'Sugar',
        'Vegetable oil',
        'Honey',
        'Salt',
        'Sodium bicarbonate',
      ],
      allergens: ['Gluten (wheat)'],
      nutrition: { energy: '420 kcal', protein: '5 g', carbohydrate: '78 g', fat: '10 g' },
      servingSize: '50 g',
      dietaryAttributes: ['Vegetarian'],
    },
    tags: ['graham-cracker', 'crumbs', 'crust', 'baking'],
    createdAt: '2025-03-08T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1017-001', '300 g Bag', 300, 395, 45, 1),
      makeVariant('BKP-1017-002', '600 g Bag', 600, 645, 35, 2),
    ],
  },
  {
    id: 1018,
    slug: 'cake-flour',
    name: 'Cake Flour',
    description:
      'Extra-fine soft wheat flour with low protein content. Bleached for a tender crumb in sponge cakes, chiffon cakes, and delicate pastry.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'cake-flour',
    baseFacts: {
      texture: 'Ultra-fine silky powder',
      colour: 'Bright white',
      source: 'Soft wheat endosperm, bleached and finely milled',
      intendedUse: 'Sponge cakes, chiffon cakes, angel food cakes, and delicate pastry',
      storage: 'Store in a cool dry place. Use within 8 months.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Ultra-fine silky powder',
      colour: 'Bright white',
      source: 'Soft wheat endosperm, bleached and finely milled',
      intendedUse: 'Sponge cakes, chiffon cakes, angel food cakes, and delicate pastry',
      storage: 'Store in a cool dry place. Use within 8 months.',
      consumptionClassification: 'food',
      ingredients: ['Wheat flour', 'Niacin', 'Iron', 'Thiamine', 'Riboflavin', 'Folic acid'],
      allergens: ['Gluten (wheat)'],
      nutrition: { energy: '360 kcal', protein: '7 g', carbohydrate: '78 g', fat: '0.8 g' },
      servingSize: '100 g',
      dietaryAttributes: ['Vegetarian'],
    },
    tags: ['flour', 'cake', 'pastry', 'low-protein'],
    createdAt: '2025-03-09T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1018-001', '500 g Box', 500, 345, 40, 1),
      makeVariant('BKP-1018-002', '1 kg Box', 1000, 545, 28, 2),
    ],
  },
  {
    id: 1019,
    slug: 'vital-wheat-gluten',
    name: 'Vital Wheat Gluten',
    description:
      'Concentrated wheat gluten flour with 75% protein. Added to bread doughs, seitan, and plant-based meats for improved elasticity, chew, and protein content.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'vital-wheat-gluten',
    baseFacts: {
      texture: 'Fine flour-like powder',
      colour: 'Pale tan',
      source: 'Washed wheat flour, dried to retain gluten protein',
      intendedUse: 'Bread improver, seitan production, plant-based protein source',
      storage: 'Store in a cool dry place in a sealed container.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine flour-like powder',
      colour: 'Pale tan',
      source: 'Washed wheat flour, dried to retain gluten protein',
      intendedUse: 'Bread improver, seitan production, plant-based protein source',
      storage: 'Store in a cool dry place in a sealed container.',
      consumptionClassification: 'food',
      ingredients: ['Wheat gluten'],
      allergens: ['Gluten (wheat)'],
      nutrition: { energy: '370 kcal', protein: '75 g', carbohydrate: '14 g', fat: '1 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Vegetarian', 'High-protein'],
    },
    tags: ['gluten', 'seitan', 'bread-improver', 'protein'],
    createdAt: '2025-03-10T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1019-001', '500 g Bag', 500, 645, 30, 1),
      makeVariant('BKP-1019-002', '1 kg Bag', 1000, 1095, 20, 2),
    ],
  },
  {
    id: 1020,
    slug: 'whey-powder',
    name: 'Whey Powder',
    description:
      'Sweet whey powder from cheese production. Adds protein, browning, and dairy richness to breads, bars, shakes, and savoury or sweet baked goods.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'whey-powder',
    baseFacts: {
      texture: 'Fine flowing powder',
      colour: 'Cream to pale yellow',
      source: 'Dried sweet whey from cheese manufacturing',
      intendedUse: 'Baking ingredient, protein enrichment, browning agent',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine flowing powder',
      colour: 'Cream to pale yellow',
      source: 'Dried sweet whey from cheese manufacturing',
      intendedUse: 'Baking ingredient, protein enrichment, browning agent',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
      ingredients: ['Sweet whey powder'],
      allergens: ['Milk'],
      nutrition: { energy: '350 kcal', protein: '12 g', carbohydrate: '73 g', fat: '1 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['whey', 'dairy', 'protein', 'baking', 'browning'],
    createdAt: '2025-03-11T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1020-001', '500 g Bag', 500, 495, 38, 1),
      makeVariant('BKP-1020-002', '1 kg Bag', 1000, 845, 25, 2),
    ],
  },
  {
    id: 1021,
    slug: 'meringue-powder',
    name: 'Meringue Powder',
    description:
      'Dried egg white powder with sugar and stabilisers for royal icing, meringues, and macarons. Replaces fresh egg whites reliably in humid conditions.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'meringue-powder',
    baseFacts: {
      texture: 'Fine white powder',
      colour: 'White',
      source: 'Dried egg albumen, sugar, cornstarch, gum arabic',
      intendedUse: 'Royal icing, meringue cookies, macarons, and egg-white decoration',
      storage: 'Store in a cool dry place. Once opened, use within 6 months.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine white powder',
      colour: 'White',
      source: 'Dried egg albumen, sugar, cornstarch, gum arabic',
      intendedUse: 'Royal icing, meringue cookies, macarons, and egg-white decoration',
      storage: 'Store in a cool dry place. Once opened, use within 6 months.',
      consumptionClassification: 'food',
      ingredients: ['Sugar', 'Dried egg albumen', 'Cornstarch', 'Gum arabic', 'Cream of tartar'],
      allergens: ['Egg'],
      nutrition: { energy: '380 kcal', protein: '10 g', carbohydrate: '85 g', fat: '0 g' },
      servingSize: '15 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['meringue', 'icing', 'egg-white', 'decoration'],
    createdAt: '2025-03-12T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1021-001', '230 g Tub', 230, 745, 25, 1),
      makeVariant('BKP-1021-002', '450 g Tub', 450, 1195, 18, 2),
    ],
  },
  {
    id: 1022,
    slug: 'gelatin-powder',
    name: 'Gelatin Powder',
    description:
      'Unflavoured bovine gelatin powder, 220 bloom strength. Used for jellies, mousses, marshmallows, gummy confectionery, and culinary gelling applications.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'gelatin-powder',
    baseFacts: {
      texture: 'Coarse granular powder',
      colour: 'Pale straw to colourless',
      source: 'Bovine hide and bone collagen, hydrolysed and dried',
      intendedUse: 'Gelling agent for desserts, confectionery, and culinary preparations',
      storage: 'Store in a cool dry place. Avoid exposure to moisture.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Coarse granular powder',
      colour: 'Pale straw to colourless',
      source: 'Bovine hide and bone collagen, hydrolysed and dried',
      intendedUse: 'Gelling agent for desserts, confectionery, and culinary preparations',
      storage: 'Store in a cool dry place. Avoid exposure to moisture.',
      consumptionClassification: 'food',
      ingredients: ['Bovine gelatin'],
      allergens: [],
      nutrition: { energy: '350 kcal', protein: '88 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '7 g',
      dietaryAttributes: ['Gluten-free', 'Dairy-free'],
    },
    tags: ['gelatin', 'gelling', 'jelly', 'confectionery'],
    createdAt: '2025-03-13T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1022-001', '200 g Bag', 200, 695, 30, 1),
      makeVariant('BKP-1022-002', '500 g Bag', 500, 1295, 20, 2),
    ],
  },
  {
    id: 1023,
    slug: 'buttermilk-powder',
    name: 'Buttermilk Powder',
    description:
      'Spray-dried cultured buttermilk powder for pancakes, biscuits, dressings, and baked goods. Adds tangy dairy flavour without needing fresh buttermilk on hand.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'buttermilk-powder',
    baseFacts: {
      texture: 'Fine cream-coloured powder',
      colour: 'Cream to pale yellow',
      source: 'Cultured buttermilk, spray-dried',
      intendedUse: 'Baking and cooking ingredient replacing liquid buttermilk',
      storage: 'Store in a cool dry place. Keep sealed; product is hygroscopic.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine cream-coloured powder',
      colour: 'Cream to pale yellow',
      source: 'Cultured buttermilk, spray-dried',
      intendedUse: 'Baking and cooking ingredient replacing liquid buttermilk',
      storage: 'Store in a cool dry place. Keep sealed; product is hygroscopic.',
      consumptionClassification: 'food',
      ingredients: ['Cultured buttermilk powder'],
      allergens: ['Milk'],
      nutrition: { energy: '360 kcal', protein: '34 g', carbohydrate: '50 g', fat: '1 g' },
      servingSize: '25 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['buttermilk', 'dairy', 'baking', 'pancakes'],
    createdAt: '2025-03-14T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('BKP-1023-001', '300 g Tub', 300, 645, 28, 1, { compareAtPriceCents: 795 }),
      makeVariant('BKP-1023-002', '600 g Tub', 600, 1095, 20, 2),
    ],
  },
  {
    id: 1024,
    slug: 'coconut-flour',
    name: 'Coconut Flour',
    description:
      'Defatted coconut meat flour with high fibre and low carbohydrate content. A grain-free alternative for paleo and keto baking with mild coconut aroma.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'coconut-flour',
    baseFacts: {
      texture: 'Soft fine powder, slightly clumpy',
      colour: 'Ivory white',
      source: 'Dried and defatted coconut meat, finely ground',
      intendedUse: 'Grain-free and gluten-free baking, absorbs significant liquid',
      storage: 'Store in a cool dry place. Seal tightly after opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Soft fine powder, slightly clumpy',
      colour: 'Ivory white',
      source: 'Dried and defatted coconut meat, finely ground',
      intendedUse: 'Grain-free and gluten-free baking, absorbs significant liquid',
      storage: 'Store in a cool dry place. Seal tightly after opening.',
      consumptionClassification: 'food',
      ingredients: ['Coconut flour'],
      allergens: ['Tree nuts (coconut)'],
      nutrition: {
        energy: '360 kcal',
        protein: '18 g',
        carbohydrate: '18 g',
        fat: '9 g',
        fibre: '38 g',
      },
      servingSize: '30 g',
      dietaryAttributes: ['Gluten-free', 'Grain-free', 'Vegan', 'High-fibre'],
    },
    tags: ['coconut', 'flour', 'gluten-free', 'grain-free', 'paleo'],
    createdAt: '2025-03-15T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1024-001', '500 g Bag', 500, 745, 30, 1),
      makeVariant('BKP-1024-002', '1 kg Bag', 1000, 1295, 20, 2),
    ],
  },
  {
    id: 1025,
    slug: 'instant-yeast',
    name: 'Instant Yeast',
    description:
      'Fast-acting instant dried yeast. No proofing required; add directly to dry ingredients. Produces reliable, consistent rise in all yeasted doughs.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'instant-yeast',
    baseFacts: {
      texture: 'Fine granulated rods',
      colour: 'Tan to light brown',
      source: 'Saccharomyces cerevisiae, dried and vacuum-packed',
      intendedUse: 'Leavening agent for bread, pizza, rolls, and sweet doughs',
      storage: 'Store in a cool dry place. Refrigerate after opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine granulated rods',
      colour: 'Tan to light brown',
      source: 'Saccharomyces cerevisiae, dried and vacuum-packed',
      intendedUse: 'Leavening agent for bread, pizza, rolls, and sweet doughs',
      storage: 'Store in a cool dry place. Refrigerate after opening.',
      consumptionClassification: 'food',
      ingredients: ['Dried yeast (Saccharomyces cerevisiae)', 'Sorbitan monostearate (emulsifier)'],
      allergens: [],
      nutrition: { energy: '320 kcal', protein: '42 g', carbohydrate: '38 g', fat: '4 g' },
      servingSize: '7 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['yeast', 'bread', 'leavening', 'instant'],
    createdAt: '2025-03-16T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1025-001', '125 g Tin', 125, 295, 50, 1),
      makeVariant('BKP-1025-002', '500 g Vacuum Pack', 500, 745, 30, 2),
    ],
  },
  {
    id: 1026,
    slug: 'rice-flour',
    name: 'Rice Flour',
    description:
      'Finely milled white rice flour, naturally gluten-free. Suitable for noodles, batters, dumplings, and gluten-free baking blends with neutral flavour.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'rice-flour',
    baseFacts: {
      texture: 'Fine soft powder',
      colour: 'Bright white',
      source: 'Milled polished white rice',
      intendedUse: 'Gluten-free baking, batters, thickening, and Asian cooking',
      storage: 'Store in a cool dry place in an airtight container.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine soft powder',
      colour: 'Bright white',
      source: 'Milled polished white rice',
      intendedUse: 'Gluten-free baking, batters, thickening, and Asian cooking',
      storage: 'Store in a cool dry place in an airtight container.',
      consumptionClassification: 'food',
      ingredients: ['White rice flour'],
      allergens: [],
      nutrition: { energy: '365 kcal', protein: '6 g', carbohydrate: '80 g', fat: '1 g' },
      servingSize: '100 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['rice', 'flour', 'gluten-free', 'asian-cooking'],
    createdAt: '2025-03-17T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1026-001', '500 g Bag', 500, 345, 42, 1),
      makeVariant('BKP-1026-002', '1 kg Bag', 1000, 545, 30, 2),
    ],
  },
  {
    id: 1027,
    slug: 'custard-powder',
    name: 'Custard Powder',
    description:
      'Traditional vanilla custard powder blend of cornstarch, sugar, and flavouring. Just add milk and heat for smooth, pour-over custard in minutes.',
    category: 'Baking & Pantry',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'custard-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Pale yellow',
      source: 'Cornstarch, sugar, natural vanilla flavouring, annatto colour',
      intendedUse: 'Quick custard dessert preparation with milk',
      storage: 'Store in a cool dry place. Use within 4 weeks of opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Pale yellow',
      source: 'Cornstarch, sugar, natural vanilla flavouring, annatto colour',
      intendedUse: 'Quick custard dessert preparation with milk',
      storage: 'Store in a cool dry place. Use within 4 weeks of opening.',
      consumptionClassification: 'food',
      ingredients: ['Cornstarch', 'Sugar', 'Natural vanilla flavour', 'Annatto (colour)', 'Salt'],
      allergens: [],
      nutrition: { energy: '350 kcal', protein: '0 g', carbohydrate: '88 g', fat: '0 g' },
      servingSize: '35 g',
      dietaryAttributes: ['Vegan (when prepared with plant milk)', 'Gluten-free'],
    },
    tags: ['custard', 'dessert', 'vanilla', 'pudding'],
    createdAt: '2025-03-18T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('BKP-1027-001', '300 g Box', 300, 395, 40, 1),
      makeVariant('BKP-1027-002', '600 g Box', 600, 645, 28, 2),
    ],
  },
]);
