import { industrializeProducts, type CatalogProduct, makeVariant } from '../model.js';

export const drinksProducts: readonly CatalogProduct[] = industrializeProducts([
  {
    id: 14,
    slug: 'matcha-green-tea-powder',
    name: 'Matcha Green Tea Powder',
    description:
      'Japanese ceremonial-grade matcha powder, stone-ground from shade-grown tencha leaves. Vibrant green colour for traditional whisked tea or latte preparation.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'matcha-green-tea-powder',
    baseFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Vibrant green',
      source: 'Shade-grown Camellia sinensis leaves, stone-ground',
      intendedUse: 'Tea preparation, lattes, smoothies, and baking',
      storage: 'Store in a cool dark place. Use within 2 months of opening for best colour.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Vibrant green',
      source: 'Shade-grown Camellia sinensis leaves, stone-ground',
      intendedUse: 'Tea preparation, lattes, smoothies, and baking',
      storage: 'Store in a cool dark place. Use within 2 months of opening for best colour.',
      consumptionClassification: 'food',
      ingredients: ['Green tea powder (Camellia sinensis)'],
      allergens: [],
      nutrition: { energy: '320 kcal', protein: '30 g', carbohydrate: '40 g', fat: '5 g' },
      servingSize: '2 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'No added sugar'],
    },
    tags: ['matcha', 'green-tea', 'japanese', 'ceremonial'],
    createdAt: '2025-01-14T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-0014-001', '30 g Tin', 30, 1895, 28, 1),
      makeVariant('DRK-0014-002', '100 g Tin', 100, 4295, 15, 2),
    ],
  },
  {
    id: 15,
    slug: 'instant-coffee',
    name: 'Instant Coffee',
    description:
      'Freeze-dried single-origin Arabica instant coffee. Rich, smooth flavour with no bitterness, dissolving instantly in hot or cold water for a quick cup.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'instant-coffee',
    baseFacts: {
      texture: 'Coarse granular crystals',
      colour: 'Dark brown',
      source: '100% Arabica coffee beans, brewed and freeze-dried',
      intendedUse: 'Instant hot or iced coffee preparation',
      storage: 'Store in a cool dry place. Seal tightly after each use.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Coarse granular crystals',
      colour: 'Dark brown',
      source: '100% Arabica coffee beans, brewed and freeze-dried',
      intendedUse: 'Instant hot or iced coffee preparation',
      storage: 'Store in a cool dry place. Seal tightly after each use.',
      consumptionClassification: 'food',
      ingredients: ['Freeze-dried Arabica coffee'],
      allergens: [],
      nutrition: { energy: '2 kcal', protein: '0 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '2 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'No added sugar'],
    },
    tags: ['coffee', 'instant', 'arabica', 'freeze-dried'],
    createdAt: '2025-01-15T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('DRK-0015-001', '100 g Jar', 100, 1495, 50, 1, { compareAtPriceCents: 1795 }),
      makeVariant('DRK-0015-002', '200 g Jar', 200, 2495, 35, 2),
    ],
  },
  {
    id: 16,
    slug: 'hot-chocolate-mix',
    name: 'Hot Chocolate Mix',
    description:
      'Rich drinking chocolate powder made with real cocoa and a touch of sugar. Simply stir into hot milk for a creamy, comforting drink.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'hot-chocolate-mix',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Medium brown',
      source: 'Cocoa powder, sugar, dried milk solids',
      intendedUse: 'Hot chocolate drink preparation with hot milk or water',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Medium brown',
      source: 'Cocoa powder, sugar, dried milk solids',
      intendedUse: 'Hot chocolate drink preparation with hot milk or water',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
      ingredients: ['Sugar', 'Cocoa powder', 'Skimmed milk powder', 'Natural vanilla flavour'],
      allergens: ['Milk'],
      nutrition: { energy: '380 kcal', protein: '8 g', carbohydrate: '72 g', fat: '6 g' },
      servingSize: '25 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['hot-chocolate', 'cocoa', 'drink-mix', 'comfort'],
    createdAt: '2025-01-16T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-0016-001', '350 g Tub', 350, 995, 50, 1),
      makeVariant('DRK-0016-002', '700 g Tub', 700, 1695, 35, 2),
    ],
  },
  {
    id: 17,
    slug: 'lemonade-powder',
    name: 'Lemonade Powder',
    description:
      'Sharp and refreshing lemonade mix with real lemon juice powder and just the right sweetness. Add cold water and ice for a classic summer drink.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'lemonade-powder',
    baseFacts: {
      texture: 'Fine granulated powder',
      colour: 'Pale yellow',
      source: 'Sugar, lemon juice powder, citric acid',
      intendedUse: 'Instant lemonade drink preparation with cold water',
      storage: 'Store in a cool dry place. Reseal to prevent clumping.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine granulated powder',
      colour: 'Pale yellow',
      source: 'Sugar, lemon juice powder, citric acid',
      intendedUse: 'Instant lemonade drink preparation with cold water',
      storage: 'Store in a cool dry place. Reseal to prevent clumping.',
      consumptionClassification: 'food',
      ingredients: ['Sugar', 'Lemon juice powder', 'Citric acid', 'Natural lemon flavour'],
      allergens: [],
      nutrition: { energy: '380 kcal', protein: '0 g', carbohydrate: '95 g', fat: '0 g' },
      servingSize: '20 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['lemonade', 'drink-mix', 'citrus', 'summer'],
    createdAt: '2025-01-17T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-0017-001', '400 g Tub', 400, 895, 55, 1),
      makeVariant('DRK-0017-002', '800 g Tub', 800, 1495, 40, 2),
    ],
  },
  {
    id: 18,
    slug: 'chai-latte-mix',
    name: 'Chai Latte Mix',
    description:
      'Spiced tea latte powder blending black tea extract with cinnamon, cardamom, ginger, and clove. Stir into hot milk for a warming cafe-style chai.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'chai-latte-mix',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Warm tan',
      source: 'Sugar, black tea extract, dried milk, spices',
      intendedUse: 'Spiced tea latte preparation with hot milk',
      storage: 'Store in a cool dry place. Use within 3 months of opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Warm tan',
      source: 'Sugar, black tea extract, dried milk, spices',
      intendedUse: 'Spiced tea latte preparation with hot milk',
      storage: 'Store in a cool dry place. Use within 3 months of opening.',
      consumptionClassification: 'food',
      ingredients: [
        'Sugar',
        'Skimmed milk powder',
        'Black tea extract',
        'Cinnamon',
        'Cardamom',
        'Ginger',
        'Clove',
        'Natural flavours',
      ],
      allergens: ['Milk'],
      nutrition: { energy: '390 kcal', protein: '7 g', carbohydrate: '82 g', fat: '4 g' },
      servingSize: '25 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['chai', 'latte', 'tea', 'spiced', 'cafe-style'],
    createdAt: '2025-01-18T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('DRK-0018-001', '200 g Tub', 200, 1095, 35, 1, { compareAtPriceCents: 1395 }),
      makeVariant('DRK-0018-002', '400 g Tub', 400, 1895, 25, 2),
    ],
  },
  {
    id: 19,
    slug: 'cold-brew-coffee-powder',
    name: 'Cold Brew Coffee Powder',
    description:
      'Micro-ground cold brew coffee powder that dissolves completely in cold water or milk. Smooth, low-acid flavour profile from a slow cold extraction process.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'cold-brew-coffee-powder',
    baseFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Dark brown',
      source: '100% Arabica coffee, cold-brewed and spray-dried',
      intendedUse: 'Instant cold coffee preparation, dissolves in cold liquid',
      storage: 'Store in a cool dry place. Keep jar tightly sealed.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Dark brown',
      source: '100% Arabica coffee, cold-brewed and spray-dried',
      intendedUse: 'Instant cold coffee preparation, dissolves in cold liquid',
      storage: 'Store in a cool dry place. Keep jar tightly sealed.',
      consumptionClassification: 'food',
      ingredients: ['Spray-dried cold brew Arabica coffee'],
      allergens: [],
      nutrition: { energy: '3 kcal', protein: '0 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '3 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'No added sugar'],
    },
    tags: ['coffee', 'cold-brew', 'instant', 'smooth'],
    createdAt: '2025-01-19T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-0019-001', '150 g Jar', 150, 1695, 32, 1),
      makeVariant('DRK-0019-002', '300 g Jar', 300, 2895, 22, 2),
    ],
  },
  {
    id: 45,
    slug: 'drinking-chocolate',
    name: 'Drinking Chocolate',
    description:
      'Luxury Belgian-style drinking chocolate powder with high cocoa butter content. Made with real chocolate flakes for a thick, velvety hot drink.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'drinking-chocolate',
    baseFacts: {
      texture: 'Fine powder with visible chocolate flakes',
      colour: 'Deep brown',
      source: 'Belgian dark chocolate, cocoa powder, sugar',
      intendedUse: 'Luxury hot chocolate preparation with hot milk',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder with visible chocolate flakes',
      colour: 'Deep brown',
      source: 'Belgian dark chocolate, cocoa powder, sugar',
      intendedUse: 'Luxury hot chocolate preparation with hot milk',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
      ingredients: ['Sugar', 'Cocoa mass', 'Cocoa powder', 'Skimmed milk powder', 'Cocoa butter'],
      allergens: ['Milk'],
      nutrition: { energy: '420 kcal', protein: '5 g', carbohydrate: '68 g', fat: '14 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['chocolate', 'drinking-chocolate', 'belgian', 'luxury'],
    createdAt: '2025-02-14T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-0045-001', '250 g Tin', 250, 1495, 28, 1),
      makeVariant('DRK-0045-002', '500 g Tin', 500, 2495, 18, 2),
    ],
  },
  {
    id: 1028,
    slug: 'instant-latte-mix',
    name: 'Instant Latte Mix',
    description:
      'Frothy instant latte powder blending Arabica coffee with whole milk powder. Just add hot water for a creamy cafe-style latte at home in seconds.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'instant-latte-mix',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Pale tan',
      source: 'Arabica coffee, whole milk powder, sugar',
      intendedUse: 'Instant latte preparation with hot water',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Pale tan',
      source: 'Arabica coffee, whole milk powder, sugar',
      intendedUse: 'Instant latte preparation with hot water',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
      ingredients: ['Whole milk powder', 'Sugar', 'Instant Arabica coffee'],
      allergens: ['Milk'],
      nutrition: { energy: '410 kcal', protein: '12 g', carbohydrate: '62 g', fat: '13 g' },
      servingSize: '25 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['latte', 'coffee', 'instant', 'frothy'],
    createdAt: '2025-03-19T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-1028-001', '200 g Tub', 200, 1095, 40, 1),
      makeVariant('DRK-1028-002', '500 g Tub', 500, 2195, 28, 2),
    ],
  },
  {
    id: 1029,
    slug: 'mocha-powder',
    name: 'Mocha Powder',
    description:
      'Coffee and chocolate drink mix for an energising mocha. Combines instant Arabica coffee with real cocoa for a satisfying blend of two favourites.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'mocha-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Dark brown',
      source: 'Arabica coffee, cocoa powder, sugar, milk powder',
      intendedUse: 'Mocha drink preparation with hot water or milk',
      storage: 'Store in a cool dry place. Reseal after use.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Dark brown',
      source: 'Arabica coffee, cocoa powder, sugar, milk powder',
      intendedUse: 'Mocha drink preparation with hot water or milk',
      storage: 'Store in a cool dry place. Reseal after use.',
      consumptionClassification: 'food',
      ingredients: ['Sugar', 'Skimmed milk powder', 'Instant coffee', 'Cocoa powder'],
      allergens: ['Milk'],
      nutrition: { energy: '400 kcal', protein: '10 g', carbohydrate: '74 g', fat: '6 g' },
      servingSize: '25 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['mocha', 'coffee', 'chocolate', 'drink-mix'],
    createdAt: '2025-03-20T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-1029-001', '250 g Tub', 250, 995, 38, 1),
      makeVariant('DRK-1029-002', '500 g Tub', 500, 1695, 28, 2),
    ],
  },
  {
    id: 1030,
    slug: 'turmeric-latte-mix',
    name: 'Turmeric Latte Mix',
    description:
      'Golden milk latte powder with turmeric, cinnamon, ginger, and black pepper. A warming, caffeine-free spiced drink to stir into warm milk or plant milk.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'turmeric-latte-mix',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Warm golden yellow',
      source: 'Turmeric root powder, cinnamon, ginger, coconut milk powder',
      intendedUse: 'Caffeine-free golden milk latte with warm milk or milk alternative',
      storage: 'Store in a cool dry place away from direct light.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Warm golden yellow',
      source: 'Turmeric root powder, cinnamon, ginger, coconut milk powder',
      intendedUse: 'Caffeine-free golden milk latte with warm milk or milk alternative',
      storage: 'Store in a cool dry place away from direct light.',
      consumptionClassification: 'food',
      ingredients: [
        'Coconut milk powder',
        'Turmeric powder',
        'Cinnamon',
        'Ginger powder',
        'Black pepper',
      ],
      allergens: ['Tree nuts (coconut)'],
      nutrition: { energy: '370 kcal', protein: '4 g', carbohydrate: '48 g', fat: '18 g' },
      servingSize: '15 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'Caffeine-free'],
    },
    tags: ['turmeric', 'latte', 'golden-milk', 'caffeine-free', 'spiced'],
    createdAt: '2025-03-21T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-1030-001', '150 g Tub', 150, 1195, 25, 1),
      makeVariant('DRK-1030-002', '300 g Tub', 300, 1995, 18, 2),
    ],
  },
  {
    id: 1031,
    slug: 'fruit-punch-powder',
    name: 'Fruit Punch Powder',
    description:
      'Tropical fruit punch drink mix with natural fruit flavours. Orange, pineapple, and passionfruit blend for a bright, refreshing cold beverage.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'fruit-punch-powder',
    baseFacts: {
      texture: 'Fine granulated powder',
      colour: 'Pink to light red',
      source: 'Sugar, fruit juice powders, citric acid, natural flavours',
      intendedUse: 'Fruit-flavoured drink mix for cold water preparation',
      storage: 'Store in a cool dry place. Reseal to prevent moisture absorption.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine granulated powder',
      colour: 'Pink to light red',
      source: 'Sugar, fruit juice powders, citric acid, natural flavours',
      intendedUse: 'Fruit-flavoured drink mix for cold water preparation',
      storage: 'Store in a cool dry place. Reseal to prevent moisture absorption.',
      consumptionClassification: 'food',
      ingredients: [
        'Sugar',
        'Orange juice powder',
        'Pineapple juice powder',
        'Citric acid',
        'Natural passionfruit flavour',
        'Beetroot powder (colour)',
      ],
      allergens: [],
      nutrition: { energy: '385 kcal', protein: '0 g', carbohydrate: '96 g', fat: '0 g' },
      servingSize: '18 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['fruit-punch', 'tropical', 'drink-mix', 'cold-drink'],
    createdAt: '2025-03-22T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-1031-001', '350 g Tub', 350, 845, 42, 1),
      makeVariant('DRK-1031-002', '700 g Tub', 700, 1495, 30, 2),
    ],
  },
  {
    id: 1032,
    slug: 'iced-tea-powder',
    name: 'Iced Tea Powder',
    description:
      'Instant lemon iced tea powder made with real tea extract and a hint of lemon. Stir into cold water for a refreshing caffeine-containing iced tea.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'iced-tea-powder',
    baseFacts: {
      texture: 'Fine granulated powder',
      colour: 'Light amber',
      source: 'Black tea extract, sugar, lemon juice powder',
      intendedUse: 'Instant iced tea preparation with cold water',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine granulated powder',
      colour: 'Light amber',
      source: 'Black tea extract, sugar, lemon juice powder',
      intendedUse: 'Instant iced tea preparation with cold water',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
      ingredients: ['Sugar', 'Black tea extract', 'Lemon juice powder', 'Citric acid'],
      allergens: [],
      nutrition: { energy: '390 kcal', protein: '0 g', carbohydrate: '97 g', fat: '0 g' },
      servingSize: '16 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['iced-tea', 'lemon', 'drink-mix', 'refreshment'],
    createdAt: '2025-03-23T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-1032-001', '300 g Tub', 300, 795, 45, 1),
      makeVariant('DRK-1032-002', '600 g Tub', 600, 1395, 35, 2),
    ],
  },
  {
    id: 1033,
    slug: 'protein-coffee-blend',
    name: 'Protein Coffee Blend',
    description:
      'Coffee-flavoured drink mix combining instant Arabica coffee with whey protein isolate. Each serving delivers 15 g protein with your morning coffee routine.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'protein-coffee-blend',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Light brown',
      source: 'Whey protein isolate (milk), Arabica coffee, natural flavours',
      intendedUse: 'Protein-enriched coffee drink for post-workout or breakfast',
      storage: 'Store in a cool dry place. Reseal after each use.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Light brown',
      source: 'Whey protein isolate (milk), Arabica coffee, natural flavours',
      intendedUse: 'Protein-enriched coffee drink for post-workout or breakfast',
      storage: 'Store in a cool dry place. Reseal after each use.',
      consumptionClassification: 'food',
      ingredients: ['Whey protein isolate', 'Instant Arabica coffee', 'Sunflower lecithin'],
      allergens: ['Milk'],
      nutrition: { energy: '100 kcal', protein: '15 g', carbohydrate: '3 g', fat: '1 g' },
      servingSize: '25 g',
      dietaryAttributes: ['Gluten-free', 'Low-fat'],
    },
    tags: ['coffee', 'protein', 'breakfast', 'post-workout'],
    createdAt: '2025-03-24T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('DRK-1033-001', '300 g Tub', 300, 1995, 30, 1, { compareAtPriceCents: 2395 }),
      makeVariant('DRK-1033-002', '600 g Tub', 600, 3495, 20, 2),
    ],
  },
  {
    id: 1034,
    slug: 'horchata-powder',
    name: 'Horchata Powder',
    description:
      'Traditional Mexican horchata drink mix with rice flour, cinnamon, and vanilla. Stir into cold water or milk for a sweet and creamy cinnamon beverage.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'horchata-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Pale cream',
      source: 'Rice flour, sugar, cinnamon, vanilla',
      intendedUse: 'Traditional cinnamon-rice drink preparation with cold water or milk',
      storage: 'Store in a cool dry place. Keep sealed.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Pale cream',
      source: 'Rice flour, sugar, cinnamon, vanilla',
      intendedUse: 'Traditional cinnamon-rice drink preparation with cold water or milk',
      storage: 'Store in a cool dry place. Keep sealed.',
      consumptionClassification: 'food',
      ingredients: [
        'Rice flour',
        'Sugar',
        'Cinnamon',
        'Natural vanilla flavour',
        'Skimmed milk powder',
      ],
      allergens: ['Milk'],
      nutrition: { energy: '380 kcal', protein: '5 g', carbohydrate: '85 g', fat: '3 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['horchata', 'cinnamon', 'rice-drink', 'mexican'],
    createdAt: '2025-03-25T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-1034-001', '250 g Bag', 250, 895, 30, 1),
      makeVariant('DRK-1034-002', '500 g Bag', 500, 1495, 20, 2),
    ],
  },
  {
    id: 1035,
    slug: 'vanilla-milkshake-powder',
    name: 'Vanilla Milkshake Powder',
    description:
      'Creamy vanilla milkshake mix made with real milk powder and natural vanilla. Just add cold milk and blend or shake for a thick classic milkshake.',
    category: 'Drinks',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'vanilla-milkshake-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Cream white',
      source: 'Whole milk powder, sugar, vanilla extract',
      intendedUse: 'Milkshake preparation with cold milk',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Cream white',
      source: 'Whole milk powder, sugar, vanilla extract',
      intendedUse: 'Milkshake preparation with cold milk',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
      ingredients: ['Whole milk powder', 'Sugar', 'Natural vanilla extract', 'Maltodextrin'],
      allergens: ['Milk'],
      nutrition: { energy: '400 kcal', protein: '14 g', carbohydrate: '56 g', fat: '14 g' },
      servingSize: '35 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['milkshake', 'vanilla', 'drink-mix', 'creamy'],
    createdAt: '2025-03-26T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('DRK-1035-001', '350 g Tub', 350, 995, 36, 1),
      makeVariant('DRK-1035-002', '700 g Tub', 700, 1695, 24, 2),
    ],
  },
]);
