import { industrializeProducts, type CatalogProduct, makeVariant } from '../model.js';

export const gardenOutdoorsProducts: readonly CatalogProduct[] = industrializeProducts([
  {
    id: 27,
    slug: 'all-purpose-garden-fertilizer',
    name: 'All-Purpose Garden Fertilizer',
    description:
      'Balanced 10-10-10 NPK granular fertilizer for flowers, vegetables, shrubs, and lawns. Slow-release formula feeds plants evenly over 8 weeks per application.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'all-purpose-garden-fertilizer',
    baseFacts: {
      texture: 'Fine granular pellets',
      colour: 'Grey-brown',
      source: 'Ammonium phosphate, potassium chloride, urea',
      intendedUse: 'General-purpose plant nutrition for gardens and landscapes',
      storage: 'Store in a cool dry place. Keep away from moisture. Keep out of reach of children.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine granular pellets',
      colour: 'Grey-brown',
      source: 'Ammonium phosphate, potassium chloride, urea',
      intendedUse: 'General-purpose plant nutrition for gardens and landscapes',
      storage: 'Store in a cool dry place. Keep away from moisture. Keep out of reach of children.',
      consumptionClassification: 'caution',
      npk: '10-10-10',
      coverage: 'One 2.5 kg bag covers approximately 50 m2',
      application:
        'Scatter evenly around plants and lightly rake into soil surface. Water thoroughly after application. Apply every 8 weeks during growing season.',
      handling:
        'Wear gloves when handling. Avoid breathing dust. Wash hands and exposed skin after use. Do not apply before heavy rain to prevent runoff.',
    },
    tags: ['fertilizer', 'all-purpose', 'npk', 'slow-release'],
    createdAt: '2025-01-27T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-0027-001', '2.5 kg Bag', 2500, 1295, 45, 1),
      makeVariant('GDN-0027-002', '10 kg Bag', 10000, 3495, 30, 2),
    ],
  },
  {
    id: 28,
    slug: 'bone-meal',
    name: 'Bone Meal',
    description:
      'Steamed bone meal fertilizer rich in phosphorus (3-15-0) and calcium. Promotes strong root development and flowering in bulbs, shrubs, and fruiting plants.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'non-food',
    imageSetId: 'bone-meal',
    baseFacts: {
      texture: 'Coarse granular powder',
      colour: 'Grey to tan',
      source: 'Steamed and ground animal bones',
      intendedUse: 'Phosphorus and calcium supplement for root and flower development',
      storage: 'Store in a cool dry place. Keep sealed and away from animals.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Coarse granular powder',
      colour: 'Grey to tan',
      source: 'Steamed and ground animal bones',
      intendedUse: 'Phosphorus and calcium supplement for root and flower development',
      storage: 'Store in a cool dry place. Keep sealed and away from animals.',
      consumptionClassification: 'non-food',
      npk: '3-15-0',
      coverage: 'One 1.5 kg bag covers approximately 20 m2 when worked into planting holes',
      application:
        'Work into soil at the base of planting holes before placing bulbs or plants. Apply 50 g per shrub and 100 g per fruit tree at planting time. Water in well.',
      handling:
        'Wear gloves. Wash hands after use. Keep away from pets as the smell may attract digging.',
    },
    tags: ['bone-meal', 'phosphorus', 'root', 'organic'],
    createdAt: '2025-01-28T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-0028-001', '1.5 kg Bag', 1500, 895, 35, 1),
      makeVariant('GDN-0028-002', '5 kg Bag', 5000, 2195, 22, 2),
    ],
  },
  {
    id: 29,
    slug: 'blood-meal',
    name: 'Blood Meal',
    description:
      'Dried blood meal with high nitrogen content (12-0-0). A quick-acting organic fertilizer for leafy vegetables, lawns, and nitrogen-deficient garden soils.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'non-food',
    imageSetId: 'blood-meal',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'Dark reddish-brown',
      source: 'Dried and ground animal blood from food processing',
      intendedUse: 'High-nitrogen organic fertilizer for leafy growth',
      storage: 'Store in a cool dry place. Keep tightly sealed. Keep away from animals.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine granular powder',
      colour: 'Dark reddish-brown',
      source: 'Dried and ground animal blood from food processing',
      intendedUse: 'High-nitrogen organic fertilizer for leafy growth',
      storage: 'Store in a cool dry place. Keep tightly sealed. Keep away from animals.',
      consumptionClassification: 'non-food',
      npk: '12-0-0',
      coverage: 'One 1 kg bag covers approximately 15 m2',
      application:
        'Sprinkle lightly over soil surface and water in. Use sparingly: excess nitrogen can burn plants. Apply every 6-8 weeks during growing season. Do not apply near edible crop harvest time.',
      handling:
        'Wear gloves and dust mask. Avoid breathing dust. Wash hands thoroughly after handling. Keep away from pets.',
    },
    tags: ['blood-meal', 'nitrogen', 'organic', 'quick-acting'],
    createdAt: '2025-01-29T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('GDN-0029-001', '1 kg Bag', 1000, 995, 30, 1, { compareAtPriceCents: 1195 }),
      makeVariant('GDN-0029-002', '3 kg Bag', 3000, 2295, 20, 2),
    ],
  },
  {
    id: 30,
    slug: 'garden-lime',
    name: 'Garden Lime',
    description:
      'Ground limestone powder for raising soil pH in acidic gardens. Improves nutrient availability and soil structure for vegetables, lawns, and ornamental plants.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'non-food',
    imageSetId: 'garden-lime',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Grey-white',
      source: 'Ground natural limestone (calcium carbonate)',
      intendedUse: 'Soil pH adjustment for acidic soils',
      storage: 'Store in a dry place. Keep sealed to prevent caking.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Grey-white',
      source: 'Ground natural limestone (calcium carbonate)',
      intendedUse: 'Soil pH adjustment for acidic soils',
      storage: 'Store in a dry place. Keep sealed to prevent caking.',
      consumptionClassification: 'non-food',
      npk: '0-0-0 (Calcium carbonate 90%+)',
      coverage: 'One 5 kg bag treats approximately 50 m2 depending on existing soil pH',
      application:
        'Spread evenly over soil surface and fork or rotavate into top 15 cm of soil. Apply in autumn for spring planting. Do not apply at the same time as manure or nitrogen fertilizers.',
      handling:
        'Wear gloves and dust mask. Avoid breathing dust. Causes eye irritation. Wash hands after use. Do not apply to acid-loving plants such as rhododendrons, camellias, or blueberries.',
    },
    tags: ['lime', 'soil-ph', 'calcium', 'alkaline'],
    createdAt: '2025-01-30T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-0030-001', '5 kg Bag', 5000, 795, 40, 1),
      makeVariant('GDN-0030-002', '15 kg Bag', 15000, 1795, 25, 2),
    ],
  },
  {
    id: 31,
    slug: 'epsom-salt',
    name: 'Epsom Salt',
    description:
      'Magnesium sulfate heptahydrate crystals for garden use. Corrects magnesium deficiency in tomatoes, peppers, roses, and conifers. Also suitable for bath use.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'epsom-salt',
    baseFacts: {
      texture: 'Fine crystalline granules',
      colour: 'White to colourless',
      source: 'Mined or synthetic magnesium sulfate',
      intendedUse: 'Magnesium supplement for plants and household bath use',
      storage: 'Store in a cool dry place. Keep container sealed to prevent moisture absorption.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine crystalline granules',
      colour: 'White to colourless',
      source: 'Mined or synthetic magnesium sulfate',
      intendedUse: 'Magnesium supplement for plants and household bath use',
      storage: 'Store in a cool dry place. Keep container sealed to prevent moisture absorption.',
      consumptionClassification: 'caution',
      npk: '0-0-0 (Magnesium 10%, Sulfur 13%)',
      coverage: 'One 1 kg bag treats approximately 30 m2 for soil application',
      application:
        'Dissolve 15 g per litre of water for foliar spray. Apply every 2-4 weeks during growing season. For soil application, scatter 30 g per m2 and water in. Also dissolves in warm bath (250 g per bath) for personal use.',
      handling: 'Wash hands after handling. Do not ingest. Avoid contact with eyes.',
    },
    tags: ['epsom-salt', 'magnesium', 'fertilizer', 'bath'],
    createdAt: '2025-01-31T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-0031-001', '1 kg Bag', 1000, 495, 55, 1),
      makeVariant('GDN-0031-002', '5 kg Bag', 5000, 1695, 35, 2),
    ],
  },
  {
    id: 32,
    slug: 'slow-release-plant-food',
    name: 'Slow-Release Plant Food',
    description:
      'Controlled-release granular plant food with 14-14-14 NPK plus trace elements. One application feeds container plants, hanging baskets, and beds for up to 6 months.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'slow-release-plant-food',
    baseFacts: {
      texture: 'Small uniform granules',
      colour: 'Light blue-grey',
      source: 'Polymer-coated urea, ammonium phosphate, potassium sulfate, trace elements',
      intendedUse: 'Long-term controlled-release feeding for container and garden plants',
      storage: 'Store in a cool dry place. Keep sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Small uniform granules',
      colour: 'Light blue-grey',
      source: 'Polymer-coated urea, ammonium phosphate, potassium sulfate, trace elements',
      intendedUse: 'Long-term controlled-release feeding for container and garden plants',
      storage: 'Store in a cool dry place. Keep sealed.',
      consumptionClassification: 'caution',
      npk: '14-14-14',
      coverage: 'One 1 kg bag feeds approximately 20 container plants for 6 months',
      application:
        'Mix into potting compost at 3 g per litre of compost before planting. For established plants, scatter on soil surface and lightly work in. Each application lasts 5-6 months.',
      handling: 'Wear gloves. Wash hands after use. Avoid over-application near watercourses.',
    },
    tags: ['fertilizer', 'slow-release', 'controlled-release', 'container'],
    createdAt: '2025-02-01T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-0032-001', '1 kg Tub', 1000, 1395, 40, 1),
      makeVariant('GDN-0032-002', '3 kg Tub', 3000, 3195, 25, 2),
    ],
  },
  {
    id: 41,
    slug: 'kelp-meal',
    name: 'Kelp Meal',
    description:
      'Dried and ground seaweed meal from Atlantic kelp (Ascophyllum nodosum). Rich in trace minerals, natural growth hormones, and organic matter for soil conditioning.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'non-food',
    imageSetId: 'kelp-meal',
    baseFacts: {
      texture: 'Coarse fibrous powder',
      colour: 'Dark green-brown',
      source: 'Dried Atlantic kelp, mechanically ground',
      intendedUse: 'Organic soil conditioner and trace mineral supplement',
      storage: 'Store in a cool dry place. Keep sealed; product is hygroscopic.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Coarse fibrous powder',
      colour: 'Dark green-brown',
      source: 'Dried Atlantic kelp, mechanically ground',
      intendedUse: 'Organic soil conditioner and trace mineral supplement',
      storage: 'Store in a cool dry place. Keep sealed; product is hygroscopic.',
      consumptionClassification: 'non-food',
      npk: '1-0-2',
      coverage: 'One 2 kg bag conditions approximately 20 m2 of garden soil',
      application:
        'Dig into soil at 100 g per m2 before planting. For established plants, work lightly into topsoil and water. Can also be steeped in water to make a liquid feed.',
      handling: 'Wash hands after handling. Avoid breathing dust. Store away from moisture.',
    },
    tags: ['kelp', 'seaweed', 'organic', 'trace-minerals'],
    createdAt: '2025-02-10T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-0041-001', '2 kg Bag', 2000, 1495, 28, 1),
      makeVariant('GDN-0041-002', '5 kg Bag', 5000, 2995, 18, 2),
    ],
  },
  {
    id: 42,
    slug: 'rock-phosphate',
    name: 'Rock Phosphate',
    description:
      'Natural mineral phosphate powder for slow-release phosphorus replenishment. Ideal base dressing for new beds, shrub borders, and fruit tree planting.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'non-food',
    imageSetId: 'rock-phosphate',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Grey-brown',
      source: 'Mined phosphate rock, finely ground',
      intendedUse: 'Long-term phosphorus soil amendment for gardens',
      storage: 'Store in a dry place. Keep sealed to prevent dust.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Grey-brown',
      source: 'Mined phosphate rock, finely ground',
      intendedUse: 'Long-term phosphorus soil amendment for gardens',
      storage: 'Store in a dry place. Keep sealed to prevent dust.',
      consumptionClassification: 'non-food',
      npk: '0-3-0 (27% total phosphate)',
      coverage: 'One 5 kg bag treats approximately 40 m2',
      application:
        'Dig into soil at 120 g per m2 when preparing new beds. Best applied in autumn for spring planting. Works slowly over 2-3 years; combine with organic matter for best results.',
      handling: 'Wear dust mask and gloves. Avoid breathing fine dust. Wash hands after use.',
    },
    tags: ['phosphate', 'mineral', 'slow-release', 'soil-amendment'],
    createdAt: '2025-02-11T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-0042-001', '5 kg Bag', 5000, 1095, 22, 1),
      makeVariant('GDN-0042-002', '15 kg Bag', 15000, 2495, 15, 2),
    ],
  },
  {
    id: 1042,
    slug: 'npk-boost',
    name: 'NPK Boost',
    description:
      'Concentrated 20-20-20 water-soluble plant feed powder. Dissolves completely for use in watering cans, drip systems, and foliar feeding of vegetables and flowers.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'npk-boost',
    baseFacts: {
      texture: 'Fine soluble crystalline powder',
      colour: 'Blue-green',
      source: 'Urea, monoammonium phosphate, potassium nitrate, trace elements',
      intendedUse: 'Quick-acting soluble plant feed for all garden plants',
      storage: 'Store in a cool dry place. Keep container closed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine soluble crystalline powder',
      colour: 'Blue-green',
      source: 'Urea, monoammonium phosphate, potassium nitrate, trace elements',
      intendedUse: 'Quick-acting soluble plant feed for all garden plants',
      storage: 'Store in a cool dry place. Keep container closed.',
      consumptionClassification: 'caution',
      npk: '20-20-20',
      coverage: 'One 500 g tub makes up to 500 litres of feed solution',
      application:
        'Dissolve 1 g per litre of water. Apply weekly during growing season. Use immediately after mixing. Do not apply in full sun.',
      handling: 'Keep out of reach of children. Wash hands after use. Avoid contact with eyes.',
    },
    tags: ['fertilizer', 'soluble', 'balanced', 'quick-feed'],
    createdAt: '2025-04-02T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-1042-001', '500 g Tub', 500, 995, 42, 1),
      makeVariant('GDN-1042-002', '1 kg Tub', 1000, 1695, 30, 2),
      makeVariant('GDN-1042-003', '5 kg Tub', 5000, 5995, 18, 3),
    ],
  },
  {
    id: 1043,
    slug: 'lawn-feed',
    name: 'Lawn Feed',
    description:
      'Spring and summer lawn fertilizer with 15-5-10 NPK plus iron for deep greening. Fine granular formulation spreads evenly for a lush, weed-resistant lawn.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'lawn-feed',
    baseFacts: {
      texture: 'Fine granular powder with iron specks',
      colour: 'Grey-green with dark specks',
      source: 'Urea, ammonium sulfate, potassium chloride, ferrous sulfate',
      intendedUse: 'Seasonal lawn feeding for colour, density, and health',
      storage: 'Store in a cool dry place. Keep away from moisture.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine granular powder with iron specks',
      colour: 'Grey-green with dark specks',
      source: 'Urea, ammonium sulfate, potassium chloride, ferrous sulfate',
      intendedUse: 'Seasonal lawn feeding for colour, density, and health',
      storage: 'Store in a cool dry place. Keep away from moisture.',
      consumptionClassification: 'caution',
      npk: '15-5-10',
      coverage: 'One 10 kg bag covers approximately 300 m2 of lawn',
      application:
        'Apply evenly using a spreader at 35 g per m2. Water in within 48 hours if no rain. Apply every 8-10 weeks from March to September. Keep off lawns until product has been watered in.',
      handling:
        'Wear gloves when spreading. Wash hands after use. Keep pets off treated area for 48 hours. Avoid over-application near ponds or watercourses.',
    },
    tags: ['lawn', 'feed', 'greening', 'iron'],
    createdAt: '2025-04-03T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('GDN-1043-001', '10 kg Bag', 10000, 2295, 35, 1, { compareAtPriceCents: 2795 }),
      makeVariant('GDN-1043-002', '25 kg Bag', 25000, 4495, 20, 2),
    ],
  },
  {
    id: 1044,
    slug: 'tomato-feed',
    name: 'Tomato Feed',
    description:
      'High-potassium tomato fertilizer powder with 8-4-12 NPK plus magnesium and seaweed extract. Promotes flowering, fruit set, and flavour in tomatoes and other fruiting crops.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'tomato-feed',
    baseFacts: {
      texture: 'Fine soluble powder',
      colour: 'Pale pink-brown',
      source: 'Potassium sulfate, ammonium phosphate, magnesium sulfate, seaweed extract',
      intendedUse: 'Specialist feed for tomatoes, peppers, aubergines, and fruiting crops',
      storage: 'Store in a cool dry place. Use within 3 months of opening.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine soluble powder',
      colour: 'Pale pink-brown',
      source: 'Potassium sulfate, ammonium phosphate, magnesium sulfate, seaweed extract',
      intendedUse: 'Specialist feed for tomatoes, peppers, aubergines, and fruiting crops',
      storage: 'Store in a cool dry place. Use within 3 months of opening.',
      consumptionClassification: 'caution',
      npk: '8-4-12',
      coverage: 'One 1 kg tub makes up to 200 litres of feed',
      application:
        'Dissolve 5 g per litre of water. Apply twice weekly once first flowers appear. Water into soil around plant base, not over leaves. Increase frequency during hot weather.',
      handling:
        'Wash hands after use. Store away from children and pets. Do not apply to leafy crops.',
    },
    tags: ['tomato', 'potassium', 'fruit', 'feed'],
    createdAt: '2025-04-04T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-1044-001', '1 kg Tub', 1000, 1095, 38, 1),
      makeVariant('GDN-1044-002', '3 kg Tub', 3000, 2695, 25, 2),
    ],
  },
  {
    id: 1045,
    slug: 'soil-conditioner',
    name: 'Soil Conditioner',
    description:
      'Powdered soil improver combining humic acid, mycorrhizal fungi, and beneficial bacteria. Enhances soil structure, water retention, and nutrient uptake in all soil types.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'non-food',
    imageSetId: 'soil-conditioner',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Dark brown',
      source: 'Leonardite (humic acid), mycorrhizal spore culture, beneficial bacillus strains',
      intendedUse: 'Biological soil improvement and root zone enhancement',
      storage: 'Store in a cool dry place. Use within 12 months for best biological activity.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Dark brown',
      source: 'Leonardite (humic acid), mycorrhizal spore culture, beneficial bacillus strains',
      intendedUse: 'Biological soil improvement and root zone enhancement',
      storage: 'Store in a cool dry place. Use within 12 months for best biological activity.',
      consumptionClassification: 'non-food',
      npk: 'Trace only',
      coverage: 'One 500 g tub treats approximately 50 m2 or 100 planting holes',
      application:
        'Mix 5 g into the planting hole or 10 g per m2 worked into the topsoil. Water in thoroughly after application. Apply once per season, ideally in spring.',
      handling:
        'Wash hands after handling. Avoid breathing dust. Store away from direct light and heat.',
    },
    tags: ['soil', 'conditioner', 'mycorrhizal', 'humic-acid'],
    createdAt: '2025-04-05T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-1045-001', '500 g Tub', 500, 1195, 25, 1),
      makeVariant('GDN-1045-002', '1 kg Tub', 1000, 1995, 18, 2),
    ],
  },
  {
    id: 1046,
    slug: 'moss-killer',
    name: 'Moss Killer',
    description:
      'Ferrous sulfate-based moss control powder for lawns and hard surfaces. Kills moss within days and greens the lawn in a single application without harming grass.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'moss-killer',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'Pale green-grey',
      source: 'Ferrous sulfate heptahydrate, ammonium sulfate, sand carrier',
      intendedUse: 'Moss control on lawns, paths, patios, and driveways',
      storage: 'Store in original container. Keep dry. Keep away from children.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine granular powder',
      colour: 'Pale green-grey',
      source: 'Ferrous sulfate heptahydrate, ammonium sulfate, sand carrier',
      intendedUse: 'Moss control on lawns, paths, patios, and driveways',
      storage: 'Store in original container. Keep dry. Keep away from children.',
      consumptionClassification: 'caution',
      npk: '0-0-0',
      coverage: 'One 5 kg bag treats approximately 150 m2 of lawn',
      application:
        'Apply evenly at 35 g per m2 when moss is actively growing, typically spring or autumn. Moss will blacken within days. Rake out dead moss after 7-14 days. Do not apply during drought or frost.',
      handling:
        'Wear gloves. May stain skin, clothes, and hard surfaces brown. Wash hands after use. Keep pets off treated area for 24 hours.',
    },
    tags: ['moss', 'lawn', 'ferrous-sulfate', 'control'],
    createdAt: '2025-04-06T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-1046-001', '5 kg Bag', 5000, 1495, 30, 1),
      makeVariant('GDN-1046-002', '15 kg Bag', 15000, 3495, 18, 2),
    ],
  },
  {
    id: 1047,
    slug: 'rose-feed',
    name: 'Rose Feed',
    description:
      'Specialist rose fertilizer powder with 10-6-15 NPK plus magnesium and iron. Formulated for abundant blooms, strong stems, and rich green foliage on all rose varieties.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'caution',
    imageSetId: 'rose-feed',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'Pink-brown',
      source: 'Potassium sulfate, ammonium phosphate, magnesium, iron chelate',
      intendedUse: 'Specialist feeding for roses and flowering shrubs',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine granular powder',
      colour: 'Pink-brown',
      source: 'Potassium sulfate, ammonium phosphate, magnesium, iron chelate',
      intendedUse: 'Specialist feeding for roses and flowering shrubs',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'caution',
      npk: '10-6-15',
      coverage: 'One 2.5 kg bag feeds approximately 25 established rose bushes',
      application:
        'Scatter 100 g around each rose bush in early spring when new growth appears. Repeat after first flush of flowers in early summer. Hoe gently into soil surface and water thoroughly.',
      handling: 'Wear gloves. Wash hands after use. Do not apply to dry soil without watering in.',
    },
    tags: ['rose', 'flower', 'bloom', 'feed'],
    createdAt: '2025-04-07T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-1047-001', '2.5 kg Bag', 2500, 1495, 28, 1),
      makeVariant('GDN-1047-002', '5 kg Bag', 5000, 2595, 18, 2),
    ],
  },
  {
    id: 1048,
    slug: 'potting-mix-amendment',
    name: 'Potting Mix Amendment',
    description:
      'Powdered blend of perlite dust, coir pith, and slow-release nutrients. Mix into garden soil or potting compost to improve drainage, aeration, and moisture retention.',
    category: 'Garden & Outdoors',
    mixingGroup: 'garden-treatment',
    consumptionClassification: 'non-food',
    imageSetId: 'potting-mix-amendment',
    baseFacts: {
      texture: 'Coarse-fine blend, fluffy',
      colour: 'Grey-brown with white specks',
      source: 'Expanded perlite, coconut coir, vermiculite, organic nutrients',
      intendedUse: 'Soil and compost improver for containers and raised beds',
      storage: 'Store in a cool dry place. Keep sealed to prevent moisture ingress.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Coarse-fine blend, fluffy',
      colour: 'Grey-brown with white specks',
      source: 'Expanded perlite, coconut coir, vermiculite, organic nutrients',
      intendedUse: 'Soil and compost improver for containers and raised beds',
      storage: 'Store in a cool dry place. Keep sealed to prevent moisture ingress.',
      consumptionClassification: 'non-food',
      npk: '2-1-3',
      coverage: 'One 5 kg bag amends approximately 50 litres of compost',
      application:
        'Mix 10% by volume into potting compost before planting. For garden soil, dig in at 5 kg per 2 m2. Water well after mixing.',
      handling:
        'Wear dust mask when pouring. Avoid breathing perlite dust. Slightly moisten before mixing to reduce dust.',
    },
    tags: ['potting', 'compost', 'drainage', 'aeration'],
    createdAt: '2025-04-08T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('GDN-1048-001', '5 kg Bag', 5000, 995, 35, 1),
      makeVariant('GDN-1048-002', '15 kg Bag', 15000, 2295, 20, 2),
    ],
  },
]);
