import { industrializeProducts, type CatalogProduct, makeVariant } from '../model.js';

export const householdCleaningProducts: readonly CatalogProduct[] = industrializeProducts([
  {
    id: 20,
    slug: 'laundry-detergent-powder',
    name: 'Laundry Detergent Powder',
    description:
      'Concentrated laundry detergent powder with stain-lifting enzymes. Effective in cold water, suitable for both top-loading and front-loading washing machines.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'laundry-detergent-powder',
    baseFacts: {
      texture: 'Free-flowing granular powder',
      colour: 'White with blue specks',
      source: 'Synthetic surfactants, enzymes, oxygen bleach, soda ash',
      intendedUse: 'Machine laundry cleaning for cotton, synthetics, and blends',
      storage: 'Store in a cool dry place. Keep out of reach of children.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Free-flowing granular powder',
      colour: 'White with blue specks',
      source: 'Synthetic surfactants, enzymes, oxygen bleach, soda ash',
      intendedUse: 'Machine laundry cleaning for cotton, synthetics, and blends',
      storage: 'Store in a cool dry place. Keep out of reach of children.',
      consumptionClassification: 'caution',
      surfaces: ['Cotton', 'Synthetics', 'Blended fabrics'],
      dosage: 'One scoop (60 g) per standard load. Use slightly less for soft-water areas.',
      hazardStatement:
        'Causes serious eye irritation. Harmful to aquatic life with long-lasting effects. Avoid release to the environment.',
      handling:
        'Wash hands after handling. Wear gloves for prolonged contact. In case of eye contact, rinse cautiously with water for several minutes.',
    },
    tags: ['laundry', 'detergent', 'powder', 'enzyme'],
    createdAt: '2025-01-20T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-0020-001', '1 kg Box', 1000, 895, 55, 1),
      makeVariant('HCL-0020-002', '3 kg Box', 3000, 1995, 38, 2),
      makeVariant('HCL-0020-003', '5 kg Bucket', 5000, 2895, 30, 3),
    ],
  },
  {
    id: 21,
    slug: 'dishwasher-powder',
    name: 'Dishwasher Powder',
    description:
      'Powerful dishwasher detergent powder with rinse aid and water softener built in. Removes baked-on food, tea stains, and grease in one wash cycle.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'dishwasher-powder',
    baseFacts: {
      texture: 'Granular powder',
      colour: 'White',
      source: 'Sodium carbonate, sodium percarbonate, enzymes, citrates',
      intendedUse: 'Automatic dishwasher cleaning of dishes, glasses, and cutlery',
      storage:
        'Store in a dry place. Keep container tightly closed. Keep out of reach of children.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Granular powder',
      colour: 'White',
      source: 'Sodium carbonate, sodium percarbonate, enzymes, citrates',
      intendedUse: 'Automatic dishwasher cleaning of dishes, glasses, and cutlery',
      storage:
        'Store in a dry place. Keep container tightly closed. Keep out of reach of children.',
      consumptionClassification: 'caution',
      surfaces: ['Glass', 'Ceramic', 'Stainless steel', 'Plastic'],
      dosage:
        'One tablespoon (20 g) in the detergent compartment. Add separate rinse aid for hard water.',
      hazardStatement: 'Causes skin irritation. Causes serious eye damage. Do not breathe dust.',
      handling:
        'Avoid contact with eyes and skin. Wear gloves when handling. If in eyes, rinse continuously with water for several minutes and seek medical advice.',
    },
    tags: ['dishwasher', 'detergent', 'cleaning', 'rinse-aid'],
    createdAt: '2025-01-21T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('HCL-0021-001', '750 g Box', 750, 995, 45, 1, { compareAtPriceCents: 1195 }),
      makeVariant('HCL-0021-002', '2 kg Box', 2000, 2195, 30, 2),
    ],
  },
  {
    id: 22,
    slug: 'all-purpose-cleaner-powder',
    name: 'All-Purpose Cleaner Powder',
    description:
      'Concentrated multi-surface cleaner powder. Dissolve in water to create an effective spray or bucket solution for kitchens, bathrooms, and hard floors.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'all-purpose-cleaner-powder',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'White',
      source: 'Sodium percarbonate, surfactants, soda ash, fragrance',
      intendedUse: 'General household surface cleaning when diluted with water',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine granular powder',
      colour: 'White',
      source: 'Sodium percarbonate, surfactants, soda ash, fragrance',
      intendedUse: 'General household surface cleaning when diluted with water',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'caution',
      surfaces: ['Sealed wood', 'Tile', 'Laminate', 'Vinyl', 'Stainless steel', 'Ceramic'],
      dosage:
        'Dissolve one scoop (25 g) per 5 litres of warm water. For spray, dissolve 5 g per 500 ml.',
      hazardStatement:
        'May cause skin and eye irritation. Do not mix with other cleaning products.',
      handling: 'Avoid dust formation. Use in well-ventilated area. Wash hands after use.',
    },
    tags: ['all-purpose', 'cleaner', 'multi-surface', 'concentrate'],
    createdAt: '2025-01-22T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-0022-001', '500 g Tub', 500, 695, 50, 1),
      makeVariant('HCL-0022-002', '1 kg Tub', 1000, 1095, 38, 2),
    ],
  },
  {
    id: 23,
    slug: 'oven-cleaner-powder',
    name: 'Oven Cleaner Powder',
    description:
      'Strong alkaline cleaner powder for removing baked-on grease and carbon deposits from oven interiors, grill racks, and baking trays. Apply as a paste.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'oven-cleaner-powder',
    baseFacts: {
      texture: 'Coarse granular powder',
      colour: 'White',
      source: 'Sodium hydroxide, surfactants, thickeners',
      intendedUse: 'Heavy-duty oven and grill cleaning',
      storage: 'Store in original container. Keep dry. Keep out of reach of children.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Coarse granular powder',
      colour: 'White',
      source: 'Sodium hydroxide, surfactants, thickeners',
      intendedUse: 'Heavy-duty oven and grill cleaning',
      storage: 'Store in original container. Keep dry. Keep out of reach of children.',
      consumptionClassification: 'caution',
      surfaces: ['Enamel', 'Stainless steel', 'Ceramic oven liners'],
      dosage:
        'Mix 50 g with small amount of water to form a paste. Apply thick layer to soiled areas.',
      hazardStatement:
        'Causes severe skin burns and eye damage. May be corrosive to metals. Do not use on aluminium.',
      handling:
        'Wear protective gloves, eye protection, and long sleeves. Avoid breathing dust. If on skin, wash with plenty of water. If in eyes, rinse for several minutes and seek immediate medical attention.',
    },
    tags: ['oven', 'cleaner', 'heavy-duty', 'degreaser'],
    createdAt: '2025-01-23T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-0023-001', '300 g Tub', 300, 795, 35, 1),
      makeVariant('HCL-0023-002', '600 g Tub', 600, 1295, 25, 2),
    ],
  },
  {
    id: 24,
    slug: 'bathroom-cleaner-powder',
    name: 'Bathroom Cleaner Powder',
    description:
      'Acid-based bathroom cleaning powder targeting limescale, soap scum, and hard water stains. Safe for ceramic, porcelain, and chrome fixtures when used as directed.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'bathroom-cleaner-powder',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Citric acid, sulfamic acid, surfactants, fragrance',
      intendedUse: 'Bathroom surface cleaning, limescale and soap scum removal',
      storage: 'Store in a cool dry place. Keep away from moisture.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Citric acid, sulfamic acid, surfactants, fragrance',
      intendedUse: 'Bathroom surface cleaning, limescale and soap scum removal',
      storage: 'Store in a cool dry place. Keep away from moisture.',
      consumptionClassification: 'caution',
      surfaces: ['Ceramic', 'Porcelain', 'Chrome', 'Glass', 'Stainless steel'],
      dosage: 'Sprinkle 20 g directly onto damp surface or dissolve 30 g per litre of warm water.',
      hazardStatement:
        'Causes skin and eye irritation. Do not mix with bleach or chlorine products.',
      handling:
        'Wear gloves. Avoid contact with eyes. Use in ventilated area. Wash hands after handling.',
    },
    tags: ['bathroom', 'cleaner', 'limescale', 'soap-scum'],
    createdAt: '2025-01-24T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('HCL-0024-001', '400 g Bottle', 400, 745, 40, 1, { compareAtPriceCents: 895 }),
      makeVariant('HCL-0024-002', '800 g Bottle', 800, 1195, 28, 2),
    ],
  },
  {
    id: 25,
    slug: 'floor-cleaner-powder',
    name: 'Floor Cleaner Powder',
    description:
      'Concentrated floor cleaning powder for mopping and machine scrubbing. Suitable for tile, vinyl, laminate, and sealed wood with a fresh lemon fragrance.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'floor-cleaner-powder',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'White to pale yellow',
      source: 'Surfactants, soda ash, sodium percarbonate, lemon fragrance',
      intendedUse: 'Hard floor cleaning when diluted in mop bucket',
      storage: 'Store in a cool dry place. Keep container closed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine granular powder',
      colour: 'White to pale yellow',
      source: 'Surfactants, soda ash, sodium percarbonate, lemon fragrance',
      intendedUse: 'Hard floor cleaning when diluted in mop bucket',
      storage: 'Store in a cool dry place. Keep container closed.',
      consumptionClassification: 'caution',
      surfaces: ['Tile', 'Vinyl', 'Laminate', 'Sealed wood', 'Stone'],
      dosage:
        'Dissolve one scoop (30 g) in 5 litres of warm water. No rinsing required on most surfaces.',
      hazardStatement: 'Causes eye irritation. May cause skin irritation on prolonged contact.',
      handling:
        'Avoid contact with eyes. Gloves recommended for sensitive skin. Wash hands after use.',
    },
    tags: ['floor', 'cleaner', 'mopping', 'lemon'],
    createdAt: '2025-01-25T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-0025-001', '750 g Tub', 750, 645, 48, 1),
      makeVariant('HCL-0025-002', '2 kg Tub', 2000, 1295, 35, 2),
    ],
  },
  {
    id: 26,
    slug: 'glass-cleaner-powder',
    name: 'Glass Cleaner Powder',
    description:
      'Streak-free glass and mirror cleaner powder. Dissolve in water for a ready-to-use spray that removes fingerprints, dust, and grime without leaving residue.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'glass-cleaner-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Alcohol ethoxylates, solvents, ammonia-free formula',
      intendedUse: 'Glass, mirror, and window cleaning when diluted',
      storage: 'Store in a cool dry place. Keep away from heat.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Alcohol ethoxylates, solvents, ammonia-free formula',
      intendedUse: 'Glass, mirror, and window cleaning when diluted',
      storage: 'Store in a cool dry place. Keep away from heat.',
      consumptionClassification: 'caution',
      surfaces: ['Glass', 'Mirrors', 'Chrome', 'Stainless steel'],
      dosage: 'Dissolve 10 g per 500 ml of water in a spray bottle. Shake before use.',
      hazardStatement: 'May cause eye irritation. Flammable solid.',
      handling: 'Keep away from ignition sources. Use in ventilated area. Avoid contact with eyes.',
    },
    tags: ['glass', 'mirror', 'streak-free', 'cleaner'],
    createdAt: '2025-01-26T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-0026-001', '200 g Bottle', 200, 495, 42, 1),
      makeVariant('HCL-0026-002', '500 g Bottle', 500, 895, 30, 2),
    ],
  },
  {
    id: 43,
    slug: 'scouring-powder',
    name: 'Scouring Powder',
    description:
      'Abrasive cleaning powder with fine pumice for removing tough stains, baked-on residue, and hard water marks from sinks, tubs, tiles, and cookware.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'non-food',
    imageSetId: 'scouring-powder',
    baseFacts: {
      texture: 'Coarse granular powder',
      colour: 'White to grey',
      source: 'Calcium carbonate, fine pumice, surfactants',
      intendedUse: 'Abrasive cleaning of hard surfaces with tough stains',
      storage: 'Store in a dry place. Keep container closed.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Coarse granular powder',
      colour: 'White to grey',
      source: 'Calcium carbonate, fine pumice, surfactants',
      intendedUse: 'Abrasive cleaning of hard surfaces with tough stains',
      storage: 'Store in a dry place. Keep container closed.',
      consumptionClassification: 'non-food',
      surfaces: ['Ceramic sinks', 'Tiles', 'Enamel', 'Stainless steel', 'Cast iron'],
      dosage: 'Sprinkle onto damp surface or sponge. Scrub, then rinse thoroughly.',
      hazardStatement:
        'Do not use on soft plastics, non-stick coatings, or polished surfaces. May scratch.',
      handling: 'Avoid generating airborne dust. Gloves recommended for sensitive skin.',
    },
    tags: ['scouring', 'abrasive', 'stain-removal', 'kitchen'],
    createdAt: '2025-02-12T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-0043-001', '350 g Shaker', 350, 445, 45, 1),
      makeVariant('HCL-0043-002', '750 g Shaker', 750, 745, 30, 2),
    ],
  },
  {
    id: 44,
    slug: 'drain-unblocker-powder',
    name: 'Drain Unblocker Powder',
    description:
      'Caustic-based drain cleaner in dry powder form. Reacts with water to generate heat and clear organic blockages in kitchen and bathroom drains.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'drain-unblocker-powder',
    baseFacts: {
      texture: 'Granular powder',
      colour: 'White to off-white',
      source: 'Sodium hydroxide, aluminium granules',
      intendedUse: 'Clearing organic blockages in household drains and pipes',
      storage:
        'Store in original container. Keep in a locked cabinet. Keep away from moisture and acids.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Granular powder',
      colour: 'White to off-white',
      source: 'Sodium hydroxide, aluminium granules',
      intendedUse: 'Clearing organic blockages in household drains and pipes',
      storage:
        'Store in original container. Keep in a locked cabinet. Keep away from moisture and acids.',
      consumptionClassification: 'caution',
      surfaces: ['Metal pipes', 'PVC pipes'],
      dosage:
        'Pour 50 g into drain. Add 250 ml cold water carefully. Leave for 30 minutes. Flush with water.',
      hazardStatement:
        'Causes severe skin burns and eye damage. Reacts violently with water, releasing flammable hydrogen gas. Never use with hot water or other chemicals.',
      handling:
        'Wear protective gloves, eye protection, and face shield. Use only in well-ventilated areas. Do not inhale fumes. If on skin, remove contaminated clothing and rinse immediately. Seek urgent medical attention for eye contact.',
    },
    tags: ['drain', 'unblocker', 'caustic', 'plumbing'],
    createdAt: '2025-02-13T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-0044-001', '300 g Bottle', 300, 645, 32, 1),
      makeVariant('HCL-0044-002', '600 g Bottle', 600, 995, 22, 2),
    ],
  },
  {
    id: 1036,
    slug: 'descaler-powder',
    name: 'Descaler Powder',
    description:
      'Citric acid-based descaling powder for kettles, coffee machines, irons, and shower heads. Effectively removes mineral build-up without harsh chemicals.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'descaler-powder',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Food-grade citric acid',
      intendedUse: 'Descaling household appliances and fixtures',
      storage: 'Store in a cool dry place. Keep container sealed to prevent clumping.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Food-grade citric acid',
      intendedUse: 'Descaling household appliances and fixtures',
      storage: 'Store in a cool dry place. Keep container sealed to prevent clumping.',
      consumptionClassification: 'caution',
      surfaces: ['Stainless steel', 'Plastic (kettles)', 'Glass', 'Chrome', 'Ceramic'],
      dosage: 'Dissolve 25 g in 500 ml warm water. Run through appliance or soak affected parts.',
      hazardStatement: 'Causes eye irritation. May irritate skin on prolonged contact.',
      handling:
        'Avoid contact with eyes. Rinse hands after handling. Do not use on natural stone surfaces.',
    },
    tags: ['descaler', 'limescale', 'citric-acid', 'appliance'],
    createdAt: '2025-03-27T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-1036-001', '250 g Tub', 250, 395, 48, 1),
      makeVariant('HCL-1036-002', '500 g Tub', 500, 645, 35, 2),
    ],
  },
  {
    id: 1037,
    slug: 'mildew-remover-powder',
    name: 'Mildew Remover Powder',
    description:
      'Oxygen-based mildew and mould stain remover powder. Dissolve in warm water and apply to affected grout, sealant, and bathroom surfaces to lift stains.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'mildew-remover-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Sodium percarbonate, surfactants, soda ash',
      intendedUse: 'Removing mildew and mould stains from bathroom and kitchen surfaces',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Sodium percarbonate, surfactants, soda ash',
      intendedUse: 'Removing mildew and mould stains from bathroom and kitchen surfaces',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'caution',
      surfaces: ['Grout', 'Silicone sealant', 'Tile', 'Plastic'],
      dosage:
        'Dissolve 30 g in 500 ml warm water. Apply with sponge or spray. Leave for 15 minutes, then scrub and rinse.',
      hazardStatement:
        'Causes eye irritation. May intensify fire; oxidiser. Do not mix with acids or bleach.',
      handling:
        'Wear gloves. Avoid contact with eyes. Use in ventilated area. Wash hands after handling.',
    },
    tags: ['mildew', 'mould', 'stain-remover', 'bathroom'],
    createdAt: '2025-03-28T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-1037-001', '300 g Tub', 300, 595, 35, 1),
      makeVariant('HCL-1037-002', '600 g Tub', 600, 995, 25, 2),
    ],
  },
  {
    id: 1038,
    slug: 'carpet-cleaner-powder',
    name: 'Carpet Cleaner Powder',
    description:
      'Dry carpet cleaning powder with encapsulated cleaning agents. Sprinkle, brush in, and vacuum to lift dirt, odours, and light stains from carpets and rugs.',
    category: 'Household & Cleaning',
    mixingGroup: 'absorbents',
    consumptionClassification: 'non-food',
    imageSetId: 'carpet-cleaner-powder',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'White',
      source: 'Zeolites, surfactants, fragrance, sodium bicarbonate',
      intendedUse: 'Dry carpet and upholstery cleaning',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine granular powder',
      colour: 'White',
      source: 'Zeolites, surfactants, fragrance, sodium bicarbonate',
      intendedUse: 'Dry carpet and upholstery cleaning',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'non-food',
      surfaces: ['Carpet', 'Rugs', 'Fabric upholstery'],
      dosage:
        'Sprinkle liberally over carpet area. Brush in with stiff brush. Leave 30 minutes, then vacuum thoroughly.',
      hazardStatement: 'May cause dust irritation. Avoid breathing powder.',
      handling:
        'Open windows for ventilation. Test on inconspicuous area first. Do not use on wet carpets.',
    },
    tags: ['carpet', 'dry-cleaning', 'deodoriser', 'upholstery'],
    createdAt: '2025-03-29T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('HCL-1038-001', '500 g Shaker', 500, 745, 38, 1, { compareAtPriceCents: 895 }),
      makeVariant('HCL-1038-002', '1 kg Shaker', 1000, 1195, 28, 2),
    ],
  },
  {
    id: 1039,
    slug: 'tile-grout-cleaner',
    name: 'Tile & Grout Cleaner',
    description:
      'Concentrated alkaline tile and grout cleaning powder. Restores grout colour and removes embedded dirt from textured tiles when used with a scrubbing brush.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'caution',
    imageSetId: 'tile-grout-cleaner',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Sodium carbonate, sodium percarbonate, surfactants',
      intendedUse: 'Deep cleaning of tile surfaces and grout lines',
      storage: 'Store in a dry place. Keep container sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Sodium carbonate, sodium percarbonate, surfactants',
      intendedUse: 'Deep cleaning of tile surfaces and grout lines',
      storage: 'Store in a dry place. Keep container sealed.',
      consumptionClassification: 'caution',
      surfaces: ['Ceramic tile', 'Porcelain tile', 'Grout', 'Stone tile'],
      dosage:
        'Mix 40 g with small amount of water to form a paste. Apply to grout lines. Scrub with brush, leave 10 minutes, rinse thoroughly.',
      hazardStatement:
        'Causes skin and eye irritation. Do not use on acid-sensitive stone such as marble or limestone.',
      handling:
        'Wear gloves. Avoid prolonged skin contact. Test on small area first. Rinse surfaces well after use.',
    },
    tags: ['tile', 'grout', 'deep-clean', 'restoration'],
    createdAt: '2025-03-30T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-1039-001', '350 g Tub', 350, 645, 32, 1),
      makeVariant('HCL-1039-002', '700 g Tub', 700, 1095, 22, 2),
    ],
  },
  {
    id: 1040,
    slug: 'furniture-cleaner-powder',
    name: 'Furniture Cleaner Powder',
    description:
      'Dry wood furniture cleaning powder with natural waxes and oils. Gently cleans and conditions wood surfaces while lifting dust and fingerprints without water.',
    category: 'Household & Cleaning',
    mixingGroup: 'cleaning',
    consumptionClassification: 'non-food',
    imageSetId: 'furniture-cleaner-powder',
    baseFacts: {
      texture: 'Fine soft powder',
      colour: 'Pale cream',
      source: 'Diatomaceous earth, carnauba wax powder, orange oil powder, surfactants',
      intendedUse: 'Waterless cleaning and conditioning of finished wood furniture',
      storage: 'Store in a cool dry place. Keep container closed.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine soft powder',
      colour: 'Pale cream',
      source: 'Diatomaceous earth, carnauba wax powder, orange oil powder, surfactants',
      intendedUse: 'Waterless cleaning and conditioning of finished wood furniture',
      storage: 'Store in a cool dry place. Keep container closed.',
      consumptionClassification: 'non-food',
      surfaces: ['Finished wood', 'Veneer', 'Laminate', 'Leather'],
      dosage:
        'Sprinkle small amount onto soft cloth. Rub gently onto surface in circular motions. Buff with clean cloth.',
      hazardStatement: 'May cause dust irritation. Keep away from open flame.',
      handling:
        'Use in well-ventilated area. Test on inconspicuous area first. Do not use on unfinished wood.',
    },
    tags: ['furniture', 'wood', 'waterless', 'conditioning'],
    createdAt: '2025-03-31T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-1040-001', '200 g Tub', 200, 745, 25, 1),
      makeVariant('HCL-1040-002', '400 g Tub', 400, 1195, 18, 2),
    ],
  },
  {
    id: 1041,
    slug: 'shoe-deodorising-powder',
    name: 'Shoe Deodorising Powder',
    description:
      'Odour-absorbing foot powder with zinc oxide and baking soda. Sprinkle into shoes or trainers to neutralise odours and absorb excess moisture between wears.',
    category: 'Household & Cleaning',
    mixingGroup: 'absorbents',
    consumptionClassification: 'non-food',
    imageSetId: 'shoe-deodorising-powder',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Sodium bicarbonate, zinc oxide, cornstarch, tea tree oil powder',
      intendedUse: 'Shoe and footgear odour and moisture control',
      storage: 'Store in a cool dry place. Keep container tightly closed.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'White',
      source: 'Sodium bicarbonate, zinc oxide, cornstarch, tea tree oil powder',
      intendedUse: 'Shoe and footgear odour and moisture control',
      storage: 'Store in a cool dry place. Keep container tightly closed.',
      consumptionClassification: 'non-food',
      surfaces: ['Leather', 'Fabric', 'Synthetic shoe interiors'],
      dosage:
        'Sprinkle one teaspoon per shoe. Shake to distribute. Leave overnight and wear or tap out excess.',
      hazardStatement: 'May cause dust irritation. Avoid getting powder into eyes.',
      handling:
        'Avoid breathing dust when sprinkling. Do not apply to broken skin. Wash hands after use.',
    },
    tags: ['shoe', 'deodoriser', 'footwear', 'absorbent'],
    createdAt: '2025-04-01T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('HCL-1041-001', '100 g Shaker', 100, 395, 45, 1),
      makeVariant('HCL-1041-002', '250 g Shaker', 250, 745, 30, 2),
    ],
  },
]);
