import { industrializeProducts, type CatalogProduct, makeVariant } from '../model.js';

export const sportsNutritionProducts: readonly CatalogProduct[] = industrializeProducts([
  {
    id: 8,
    slug: 'whey-protein-isolate',
    name: 'Whey Protein Isolate',
    description:
      'Ultra-filtered whey protein isolate powder with 25 g protein per serving. Instant-mixing vanilla flavour, suitable for post-workout shakes or daily protein supplementation.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'whey-protein-isolate',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Off-white to pale cream',
      source: 'Cow milk whey, cross-flow micro-filtered',
      intendedUse: 'Protein supplementation, post-workout recovery',
      storage: 'Store in a cool dry place. Reseal pack after use.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine powder',
        colour: 'Off-white to pale cream',
        source: 'Cow milk whey, cross-flow micro-filtered',
        intendedUse: 'Protein supplementation, post-workout recovery',
        storage: 'Store in a cool dry place. Reseal pack after use.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Vanilla',
      servings: 30,
      proteinPerServing: 25,
      carbsPerServing: 2,
      ingredients: ['Whey protein isolate', 'Sunflower lecithin', 'Natural vanilla flavour'],
      allergens: ['Milk'],
      nutrition: { energy: '120 kcal', protein: '25 g', carbohydrate: '2 g', fat: '0.5 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Gluten-free', 'Low-fat', 'No added sugar'],
    },
    tags: ['whey', 'protein', 'vanilla', 'isolate'],
    createdAt: '2025-01-08T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-0008-001', '500 g Tub', 500, 2495, 42, 1),
      makeVariant('SPN-0008-002', '1 kg Bag', 1000, 3995, 35, 2, { compareAtPriceCents: 4595 }),
      makeVariant('SPN-0008-003', '2.5 kg Bag', 2500, 8495, 20, 3),
    ],
  },
  {
    id: 9,
    slug: 'creatine-monohydrate',
    name: 'Creatine Monohydrate',
    description:
      'Pure micronized creatine monohydrate powder, unflavoured and free of additives. Each 5 g serving supports muscle energy production during high-intensity exercise.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'creatine-monohydrate',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Synthetic, produced from sarcosine and cyanamide',
      intendedUse: 'Sports performance supplement for high-intensity exercise',
      storage: 'Store in a cool dry place away from moisture.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine crystalline powder',
        colour: 'White',
        source: 'Synthetic, produced from sarcosine and cyanamide',
        intendedUse: 'Sports performance supplement for high-intensity exercise',
        storage: 'Store in a cool dry place away from moisture.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Unflavoured',
      servings: 100,
      proteinPerServing: 0,
      carbsPerServing: 0,
      ingredients: ['Creatine monohydrate'],
      allergens: [],
      nutrition: { energy: '0 kcal', protein: '0 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '5 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'No additives'],
    },
    tags: ['creatine', 'monohydrate', 'unflavoured', 'micronized'],
    createdAt: '2025-01-09T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-0009-001', '250 g Tub', 250, 1495, 55, 1),
      makeVariant('SPN-0009-002', '500 g Tub', 500, 2495, 40, 2, { compareAtPriceCents: 2995 }),
      makeVariant('SPN-0009-003', '1 kg Bag', 1000, 3995, 25, 3),
    ],
  },
  {
    id: 10,
    slug: 'beetroot-powder',
    name: 'Beetroot Powder',
    description:
      'Spray-dried beetroot juice powder with naturally occurring nitrates. Mixes easily into water, smoothies, or pre-workout drinks for a deep berry colour.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'beetroot-powder',
    baseFacts: {
      texture: 'Fine soluble powder',
      colour: 'Deep burgundy red',
      source: 'Concentrated beetroot juice, spray-dried',
      intendedUse: 'Pre-workout drink ingredient, natural colour and nitrate source',
      storage: 'Store in a cool dry place. Keep away from direct light.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine soluble powder',
        colour: 'Deep burgundy red',
        source: 'Concentrated beetroot juice, spray-dried',
        intendedUse: 'Pre-workout drink ingredient, natural colour and nitrate source',
        storage: 'Store in a cool dry place. Keep away from direct light.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Earthy beetroot',
      servings: 40,
      proteinPerServing: 1,
      carbsPerServing: 4,
      ingredients: ['Beetroot juice powder', 'Maltodextrin (carrier)'],
      allergens: [],
      nutrition: { energy: '20 kcal', protein: '1 g', carbohydrate: '4 g', fat: '0 g' },
      servingSize: '5 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'No added sugar'],
    },
    tags: ['beetroot', 'nitrates', 'pre-workout', 'natural'],
    createdAt: '2025-01-10T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-0010-001', '250 g Tub', 250, 1395, 35, 1),
      makeVariant('SPN-0010-002', '500 g Bag', 500, 2295, 28, 2),
    ],
  },
  {
    id: 11,
    slug: 'pea-protein-isolate',
    name: 'Pea Protein Isolate',
    description:
      'Plant-based pea protein isolate with 80% protein content. Neutral taste, smooth texture, and suitable for shakes, baking, and savoury recipes.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'pea-protein-isolate',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Pale beige',
      source: 'Yellow pea, water-extracted and dried',
      intendedUse: 'Plant-based protein supplementation, cooking and baking ingredient',
      storage: 'Store in a cool dry place. Reseal after opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine powder',
        colour: 'Pale beige',
        source: 'Yellow pea, water-extracted and dried',
        intendedUse: 'Plant-based protein supplementation, cooking and baking ingredient',
        storage: 'Store in a cool dry place. Reseal after opening.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Unflavoured',
      servings: 33,
      proteinPerServing: 24,
      carbsPerServing: 1,
      ingredients: ['Pea protein isolate'],
      allergens: [],
      nutrition: { energy: '110 kcal', protein: '24 g', carbohydrate: '1 g', fat: '2 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'Soy-free', 'Dairy-free'],
    },
    tags: ['pea', 'protein', 'plant-based', 'vegan', 'unflavoured'],
    createdAt: '2025-01-11T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-0011-001', '500 g Bag', 500, 2495, 38, 1),
      makeVariant('SPN-0011-002', '1 kg Bag', 1000, 3995, 30, 2, { compareAtPriceCents: 4595 }),
      makeVariant('SPN-0011-003', '2.5 kg Bag', 2500, 8495, 15, 3),
    ],
  },
  {
    id: 12,
    slug: 'bcaa-powder',
    name: 'BCAA Powder',
    description:
      'Instantised branched-chain amino acid powder in a 2:1:1 ratio of leucine, isoleucine, and valine. Unflavoured for easy mixing into any drink.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'bcaa-powder',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White to off-white',
      source: 'Fermentation-derived amino acids',
      intendedUse: 'Amino acid supplementation during or after exercise',
      storage: 'Store in a cool dry place. Keep tightly sealed.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine crystalline powder',
        colour: 'White to off-white',
        source: 'Fermentation-derived amino acids',
        intendedUse: 'Amino acid supplementation during or after exercise',
        storage: 'Store in a cool dry place. Keep tightly sealed.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Unflavoured',
      servings: 60,
      proteinPerServing: 5,
      carbsPerServing: 0,
      ingredients: ['L-Leucine', 'L-Isoleucine', 'L-Valine', 'Sunflower lecithin (emulsifier)'],
      allergens: [],
      nutrition: { energy: '20 kcal', protein: '5 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '5 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'No added sugar'],
    },
    tags: ['bcaa', 'amino-acids', 'unflavoured', 'recovery'],
    createdAt: '2025-01-12T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('SPN-0012-001', '250 g Tub', 250, 1795, 32, 1, { compareAtPriceCents: 2195 }),
      makeVariant('SPN-0012-002', '500 g Tub', 500, 2995, 25, 2),
    ],
  },
  {
    id: 13,
    slug: 'electrolyte-blend',
    name: 'Electrolyte Blend',
    description:
      'Citrus-flavoured electrolyte drink mix with sodium, potassium, magnesium, and calcium. One scoop added to water supports hydration during endurance activity or hot conditions.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'electrolyte-blend',
    baseFacts: {
      texture: 'Fine granulated powder',
      colour: 'Pale yellow',
      source: 'Mineral salts, dextrose, citric acid',
      intendedUse: 'Hydration support during and after endurance exercise',
      storage: 'Store in a cool dry place. Use within 3 months of opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine granulated powder',
        colour: 'Pale yellow',
        source: 'Mineral salts, dextrose, citric acid',
        intendedUse: 'Hydration support during and after endurance exercise',
        storage: 'Store in a cool dry place. Use within 3 months of opening.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Citrus',
      servings: 40,
      proteinPerServing: 0,
      carbsPerServing: 8,
      ingredients: [
        'Dextrose',
        'Sodium chloride',
        'Potassium citrate',
        'Magnesium citrate',
        'Calcium carbonate',
        'Citric acid',
        'Natural citrus flavour',
      ],
      allergens: [],
      nutrition: { energy: '32 kcal', protein: '0 g', carbohydrate: '8 g', fat: '0 g' },
      servingSize: '10 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['electrolyte', 'hydration', 'citrus', 'endurance'],
    createdAt: '2025-01-13T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-0013-001', '300 g Tub', 300, 1495, 45, 1),
      makeVariant('SPN-0013-002', '600 g Tub', 600, 2495, 35, 2, { compareAtPriceCents: 2995 }),
    ],
  },
  {
    id: 1001,
    slug: 'casein-protein',
    name: 'Casein Protein',
    description:
      'Micellar casein protein powder with slow-digesting amino acid profile. Creamy vanilla flavour, ideal for overnight recovery or between-meal protein support.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'casein-protein',
    baseFacts: {
      texture: 'Fine creamy powder',
      colour: 'Cream white',
      source: 'Cow milk casein, micellar filtration',
      intendedUse: 'Slow-release protein for overnight recovery or extended amino acid delivery',
      storage: 'Store in a cool dry place. Reseal tightly after use.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine creamy powder',
        colour: 'Cream white',
        source: 'Cow milk casein, micellar filtration',
        intendedUse: 'Slow-release protein for overnight recovery or extended amino acid delivery',
        storage: 'Store in a cool dry place. Reseal tightly after use.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Vanilla',
      servings: 30,
      proteinPerServing: 24,
      carbsPerServing: 3,
      ingredients: ['Micellar casein', 'Sunflower lecithin', 'Natural vanilla flavour'],
      allergens: ['Milk'],
      nutrition: { energy: '118 kcal', protein: '24 g', carbohydrate: '3 g', fat: '1 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Gluten-free', 'Low-fat'],
    },
    tags: ['casein', 'protein', 'slow-release', 'vanilla'],
    createdAt: '2025-02-20T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1001-001', '500 g Tub', 500, 2695, 30, 1),
      makeVariant('SPN-1001-002', '1 kg Bag', 1000, 4495, 22, 2),
    ],
  },
  {
    id: 1002,
    slug: 'pre-workout-blend',
    name: 'Pre-Workout Blend',
    description:
      'Caffeine-based pre-workout formula with citrulline malate, beta-alanine, and B-vitamins. Berry-flavoured powder supports focus and energy before training.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'caution',
    imageSetId: 'pre-workout-blend',
    baseFacts: {
      texture: 'Fine granulated powder',
      colour: 'Pink to light red',
      source: 'Synthesised amino acids, natural caffeine, vitamins',
      intendedUse: 'Pre-exercise energy and focus support for adults',
      storage: 'Store in a cool dry place. Keep out of reach of children.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      ...({
        texture: 'Fine granulated powder',
        colour: 'Pink to light red',
        source: 'Synthesised amino acids, natural caffeine, vitamins',
        intendedUse: 'Pre-exercise energy and focus support for adults',
        storage: 'Store in a cool dry place. Keep out of reach of children.',
        consumptionClassification: 'caution',
      } as const),
      flavour: 'Mixed berry',
      servings: 30,
      proteinPerServing: 0,
      carbsPerServing: 2,
      ingredients: [
        'Citrulline malate',
        'Beta-alanine',
        'Caffeine anhydrous',
        'L-tyrosine',
        'Niacin',
        'Vitamin B6',
        'Vitamin B12',
        'Citric acid',
        'Natural berry flavour',
        'Stevia extract',
      ],
      allergens: [],
      nutrition: {
        energy: '10 kcal',
        protein: '0 g',
        carbohydrate: '2 g',
        fat: '0 g',
        caffeine: '200 mg',
      },
      servingSize: '15 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'High caffeine content'],
    },
    tags: ['pre-workout', 'caffeine', 'energy', 'focus', 'berry'],
    createdAt: '2025-02-21T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1002-001', '300 g Tub', 300, 2795, 38, 1),
      makeVariant('SPN-1002-002', '600 g Tub', 600, 4495, 25, 2, { compareAtPriceCents: 4995 }),
    ],
  },
  {
    id: 1003,
    slug: 'glutamine-powder',
    name: 'L-Glutamine Powder',
    description:
      'Pure fermented L-glutamine powder, unflavoured and odourless. A conditionally essential amino acid used as a recovery supplement alongside a balanced diet.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'glutamine-powder',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Fermentation-derived glutamine',
      intendedUse: 'Amino acid supplementation for post-exercise recovery support',
      storage: 'Store in a cool dry place. Avoid exposure to moisture.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine crystalline powder',
        colour: 'White',
        source: 'Fermentation-derived glutamine',
        intendedUse: 'Amino acid supplementation for post-exercise recovery support',
        storage: 'Store in a cool dry place. Avoid exposure to moisture.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Unflavoured',
      servings: 100,
      proteinPerServing: 5,
      carbsPerServing: 0,
      ingredients: ['L-Glutamine'],
      allergens: [],
      nutrition: { energy: '20 kcal', protein: '5 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '5 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['glutamine', 'amino-acid', 'recovery', 'unflavoured'],
    createdAt: '2025-02-22T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1003-001', '250 g Tub', 250, 1695, 36, 1),
      makeVariant('SPN-1003-002', '500 g Tub', 500, 2795, 28, 2),
    ],
  },
  {
    id: 1004,
    slug: 'collagen-peptides',
    name: 'Collagen Peptides',
    description:
      'Hydrolysed bovine collagen peptides, type I and III. Easily dissolves in hot or cold liquids. Unflavoured, suitable for coffee, smoothies, and cooking.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'collagen-peptides',
    baseFacts: {
      texture: 'Fine soluble powder',
      colour: 'White to pale cream',
      source: 'Bovine hide, enzymatic hydrolysis',
      intendedUse:
        'Dietary collagen supplementation for joint, skin, and connective tissue support',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine soluble powder',
        colour: 'White to pale cream',
        source: 'Bovine hide, enzymatic hydrolysis',
        intendedUse:
          'Dietary collagen supplementation for joint, skin, and connective tissue support',
        storage: 'Store in a cool dry place. Reseal tightly.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Unflavoured',
      servings: 40,
      proteinPerServing: 10,
      carbsPerServing: 0,
      ingredients: ['Hydrolysed bovine collagen peptides'],
      allergens: [],
      nutrition: { energy: '38 kcal', protein: '10 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '10 g',
      dietaryAttributes: ['Gluten-free', 'Dairy-free', 'No additives'],
    },
    tags: ['collagen', 'peptides', 'joint', 'unflavoured'],
    createdAt: '2025-02-23T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1004-001', '300 g Tub', 300, 2295, 42, 1),
      makeVariant('SPN-1004-002', '600 g Tub', 600, 3895, 30, 2),
    ],
  },
  {
    id: 1005,
    slug: 'beta-alanine-powder',
    name: 'Beta-Alanine Powder',
    description:
      'Pure beta-alanine powder for buffering muscle acidity during high-intensity exercise. Unflavoured, can be added to pre-workout or intra-workout drinks.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'caution',
    imageSetId: 'beta-alanine-powder',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Synthetic, produced from beta-propiolactone and ammonia',
      intendedUse: 'Sports supplement to support muscle endurance during high-intensity training',
      storage: 'Store in a cool dry place. May cause harmless tingling sensation.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      ...({
        texture: 'Fine crystalline powder',
        colour: 'White',
        source: 'Synthetic, produced from beta-propiolactone and ammonia',
        intendedUse: 'Sports supplement to support muscle endurance during high-intensity training',
        storage: 'Store in a cool dry place. May cause harmless tingling sensation.',
        consumptionClassification: 'caution',
      } as const),
      flavour: 'Unflavoured',
      servings: 100,
      proteinPerServing: 0,
      carbsPerServing: 0,
      ingredients: ['Beta-alanine'],
      allergens: [],
      nutrition: { energy: '0 kcal', protein: '0 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '3.2 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['beta-alanine', 'endurance', 'carnosine', 'unflavoured'],
    createdAt: '2025-02-24T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('SPN-1005-001', '200 g Tub', 200, 1695, 28, 1, { compareAtPriceCents: 1995 }),
      makeVariant('SPN-1005-002', '500 g Tub', 500, 3195, 20, 2),
    ],
  },
  {
    id: 1006,
    slug: 'l-carnitine-powder',
    name: 'L-Carnitine Powder',
    description:
      'Pure L-carnitine L-tartrate powder for those following a training programme. Unflavoured, dissolves in water or your preferred pre-workout drink.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'l-carnitine-powder',
    baseFacts: {
      texture: 'Fine crystalline powder',
      colour: 'White',
      source: 'Synthetic, produced from trimethyllysine',
      intendedUse: 'Amino acid derivative used alongside exercise and balanced nutrition',
      storage: 'Store in a cool dry place. Keep away from heat.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine crystalline powder',
        colour: 'White',
        source: 'Synthetic, produced from trimethyllysine',
        intendedUse: 'Amino acid derivative used alongside exercise and balanced nutrition',
        storage: 'Store in a cool dry place. Keep away from heat.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Unflavoured',
      servings: 60,
      proteinPerServing: 0,
      carbsPerServing: 0,
      ingredients: ['L-Carnitine L-tartrate'],
      allergens: [],
      nutrition: { energy: '0 kcal', protein: '0 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '2 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['carnitine', 'amino-acid', 'unflavoured'],
    createdAt: '2025-02-25T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1006-001', '100 g Tub', 100, 1495, 25, 1),
      makeVariant('SPN-1006-002', '250 g Tub', 250, 2795, 18, 2),
    ],
  },
  {
    id: 1007,
    slug: 'hmb-powder',
    name: 'HMB Powder',
    description:
      'Beta-hydroxy beta-methylbutyrate calcium salt powder. A metabolite of leucine used as a recovery supplement alongside structured resistance training.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'caution',
    imageSetId: 'hmb-powder',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'White',
      source: 'Synthetic, produced from diacetone alcohol via oxidation',
      intendedUse: 'Sports supplement intended for use alongside resistance training',
      storage: 'Store in a cool dry place. Keep out of reach of children.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      ...({
        texture: 'Fine granular powder',
        colour: 'White',
        source: 'Synthetic, produced from diacetone alcohol via oxidation',
        intendedUse: 'Sports supplement intended for use alongside resistance training',
        storage: 'Store in a cool dry place. Keep out of reach of children.',
        consumptionClassification: 'caution',
      } as const),
      flavour: 'Unflavoured',
      servings: 90,
      proteinPerServing: 0,
      carbsPerServing: 0,
      ingredients: ['Calcium beta-hydroxy-beta-methylbutyrate'],
      allergens: [],
      nutrition: { energy: '0 kcal', protein: '0 g', carbohydrate: '0 g', fat: '0 g' },
      servingSize: '1 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['hmb', 'recovery', 'leucine', 'unflavoured'],
    createdAt: '2025-02-26T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1007-001', '90 g Tub', 90, 1995, 15, 1),
      makeVariant('SPN-1007-002', '180 g Tub', 180, 3495, 10, 2),
    ],
  },
  {
    id: 1008,
    slug: 'mass-gainer',
    name: 'Mass Gainer',
    description:
      'High-calorie weight gain formula combining maltodextrin and whey protein concentrate. Chocolate flavour, designed for those needing additional caloric intake alongside training.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'mass-gainer',
    baseFacts: {
      texture: 'Fine powder blend',
      colour: 'Light brown',
      source: 'Maltodextrin (corn), whey protein concentrate (milk)',
      intendedUse: 'Weight gain supplement for increased caloric intake',
      storage: 'Store in a cool dry place. Use within 2 months of opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine powder blend',
        colour: 'Light brown',
        source: 'Maltodextrin (corn), whey protein concentrate (milk)',
        intendedUse: 'Weight gain supplement for increased caloric intake',
        storage: 'Store in a cool dry place. Use within 2 months of opening.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Chocolate',
      servings: 16,
      proteinPerServing: 28,
      carbsPerServing: 82,
      ingredients: [
        'Maltodextrin',
        'Whey protein concentrate',
        'Cocoa powder',
        'Sunflower lecithin',
        'Natural chocolate flavour',
      ],
      allergens: ['Milk'],
      nutrition: { energy: '450 kcal', protein: '28 g', carbohydrate: '82 g', fat: '3 g' },
      servingSize: '125 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['mass-gainer', 'weight-gain', 'chocolate', 'high-calorie'],
    createdAt: '2025-02-27T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1008-001', '2 kg Bag', 2000, 3295, 22, 1),
      makeVariant('SPN-1008-002', '5 kg Bag', 5000, 6495, 14, 2),
    ],
  },
  {
    id: 1009,
    slug: 'recovery-blend',
    name: 'Recovery Blend',
    description:
      'Post-workout recovery drink mix with whey protein, dextrose, and electrolytes. Strawberry flavour for convenient post-exercise replenishment.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'recovery-blend',
    baseFacts: {
      texture: 'Fine blend powder',
      colour: 'Pink',
      source: 'Whey protein (milk), dextrose (corn), mineral salts',
      intendedUse: 'Post-workout recovery drink for carbohydrate and protein replenishment',
      storage: 'Store in a cool dry place. Reseal tightly.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine blend powder',
        colour: 'Pink',
        source: 'Whey protein (milk), dextrose (corn), mineral salts',
        intendedUse: 'Post-workout recovery drink for carbohydrate and protein replenishment',
        storage: 'Store in a cool dry place. Reseal tightly.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Strawberry',
      servings: 25,
      proteinPerServing: 20,
      carbsPerServing: 35,
      ingredients: [
        'Whey protein concentrate',
        'Dextrose',
        'Sodium chloride',
        'Potassium citrate',
        'Natural strawberry flavour',
        'Beetroot powder (colour)',
      ],
      allergens: ['Milk'],
      nutrition: { energy: '230 kcal', protein: '20 g', carbohydrate: '35 g', fat: '2 g' },
      servingSize: '60 g',
      dietaryAttributes: ['Gluten-free'],
    },
    tags: ['recovery', 'post-workout', 'strawberry', 'electrolytes'],
    createdAt: '2025-02-28T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('SPN-1009-001', '750 g Tub', 750, 2695, 30, 1, { compareAtPriceCents: 3195 }),
      makeVariant('SPN-1009-002', '1.5 kg Bag', 1500, 4495, 20, 2),
    ],
  },
  {
    id: 1010,
    slug: 'greens-powder',
    name: 'Greens Powder',
    description:
      'Blend of powdered spinach, kale, spirulina, and wheatgrass. Natural green superfood mix for smoothies and juices, providing plant-based micronutrients.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'greens-powder',
    baseFacts: {
      texture: 'Fine green powder',
      colour: 'Dark green',
      source: 'Dried and milled spinach, kale, spirulina, wheatgrass',
      intendedUse: 'Daily greens supplement for smoothies and juices',
      storage: 'Store in a cool dry place. Keep out of direct light.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine green powder',
        colour: 'Dark green',
        source: 'Dried and milled spinach, kale, spirulina, wheatgrass',
        intendedUse: 'Daily greens supplement for smoothies and juices',
        storage: 'Store in a cool dry place. Keep out of direct light.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Earthy green',
      servings: 30,
      proteinPerServing: 3,
      carbsPerServing: 4,
      ingredients: [
        'Spinach powder',
        'Kale powder',
        'Spirulina powder',
        'Wheatgrass powder',
        'Barley grass powder',
      ],
      allergens: [],
      nutrition: { energy: '25 kcal', protein: '3 g', carbohydrate: '4 g', fat: '0 g' },
      servingSize: '8 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'No added sugar'],
    },
    tags: ['greens', 'superfood', 'spirulina', 'vegan', 'plant-based'],
    createdAt: '2025-03-01T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('SPN-1010-001', '200 g Tub', 200, 1995, 32, 1, { compareAtPriceCents: 2395 }),
      makeVariant('SPN-1010-002', '400 g Bag', 400, 3295, 22, 2),
    ],
  },
  {
    id: 1011,
    slug: 'energy-gel-mix',
    name: 'Energy Gel Mix',
    description:
      'Concentrated carbohydrate energy gel powder with electrolytes. Neutral flavour, measured scoop turns into an isotonic energy gel when mixed with water.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'energy-gel-mix',
    baseFacts: {
      texture: 'Fine granular powder',
      colour: 'Off-white',
      source: 'Maltodextrin (corn), fructose, mineral salts',
      intendedUse: 'Endurance fuel for running, cycling, and other prolonged exercise',
      storage: 'Store in a cool dry place. Use within 4 months of opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine granular powder',
        colour: 'Off-white',
        source: 'Maltodextrin (corn), fructose, mineral salts',
        intendedUse: 'Endurance fuel for running, cycling, and other prolonged exercise',
        storage: 'Store in a cool dry place. Use within 4 months of opening.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Neutral',
      servings: 32,
      proteinPerServing: 0,
      carbsPerServing: 40,
      ingredients: ['Maltodextrin', 'Fructose', 'Sodium chloride', 'Citric acid'],
      allergens: [],
      nutrition: { energy: '160 kcal', protein: '0 g', carbohydrate: '40 g', fat: '0 g' },
      servingSize: '40 g',
      dietaryAttributes: ['Vegan', 'Gluten-free'],
    },
    tags: ['energy-gel', 'carbohydrate', 'endurance', 'neutral'],
    createdAt: '2025-03-02T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1011-001', '500 g Bag', 500, 1995, 38, 1),
      makeVariant('SPN-1011-002', '1 kg Bag', 1000, 3295, 28, 2),
      makeVariant('SPN-1011-003', '2.5 kg Bag', 2500, 6995, 15, 3),
    ],
  },
  {
    id: 1012,
    slug: 'protein-bar-mix',
    name: 'Protein Bar Mix',
    description:
      'Dry blend of whey and casein protein with oat flour and cocoa. Just add water and chosen binders to press your own high-protein snack bars at home.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'protein-bar-mix',
    baseFacts: {
      texture: 'Coarse blend',
      colour: 'Light brown',
      source: 'Whey protein, casein (milk), oat flour, cocoa',
      intendedUse: 'Base mix for homemade high-protein snack bars',
      storage: 'Store in a cool dry place. Seal tightly after use.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Coarse blend',
        colour: 'Light brown',
        source: 'Whey protein, casein (milk), oat flour, cocoa',
        intendedUse: 'Base mix for homemade high-protein snack bars',
        storage: 'Store in a cool dry place. Seal tightly after use.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Chocolate',
      servings: 16,
      proteinPerServing: 18,
      carbsPerServing: 12,
      ingredients: [
        'Whey protein concentrate',
        'Calcium caseinate',
        'Oat flour',
        'Cocoa powder',
        'Sunflower lecithin',
      ],
      allergens: ['Milk', 'Gluten (oats)'],
      nutrition: { energy: '160 kcal', protein: '18 g', carbohydrate: '12 g', fat: '4 g' },
      servingSize: '40 g',
      dietaryAttributes: [],
    },
    tags: ['protein-bar', 'baking', 'chocolate', 'homemade'],
    createdAt: '2025-03-03T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1012-001', '500 g Bag', 500, 1895, 25, 1),
      makeVariant('SPN-1012-002', '1 kg Bag', 1000, 3195, 18, 2),
    ],
  },
  {
    id: 1013,
    slug: 'daily-protein-shake',
    name: 'Daily Protein Shake',
    description:
      'All-in-one meal replacement shake powder with whey protein, oat flour, fibre, and vitamins. Vanilla flavour for a convenient and balanced daily shake.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'daily-protein-shake',
    baseFacts: {
      texture: 'Fine powder blend',
      colour: 'Cream',
      source: 'Whey protein (milk), oat flour, vitamin and mineral premix',
      intendedUse: 'Meal replacement or supplementary nutrition shake',
      storage: 'Store in a cool dry place. Use within 4 weeks of opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine powder blend',
        colour: 'Cream',
        source: 'Whey protein (milk), oat flour, vitamin and mineral premix',
        intendedUse: 'Meal replacement or supplementary nutrition shake',
        storage: 'Store in a cool dry place. Use within 4 weeks of opening.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Vanilla',
      servings: 14,
      proteinPerServing: 22,
      carbsPerServing: 28,
      ingredients: [
        'Whey protein concentrate',
        'Oat flour',
        'Inulin (chicory fibre)',
        'Sunflower oil powder',
        'Vitamin and mineral premix',
        'Natural vanilla flavour',
      ],
      allergens: ['Milk', 'Gluten (oats)'],
      nutrition: {
        energy: '320 kcal',
        protein: '22 g',
        carbohydrate: '28 g',
        fat: '6 g',
        fibre: '5 g',
      },
      servingSize: '80 g',
      dietaryAttributes: [],
    },
    tags: ['meal-replacement', 'shake', 'vanilla', 'all-in-one'],
    createdAt: '2025-03-04T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('SPN-1013-001', '700 g Bag', 700, 2595, 28, 1, { compareAtPriceCents: 2995 }),
      makeVariant('SPN-1013-002', '1.4 kg Tub', 1400, 4395, 18, 2),
    ],
  },
  {
    id: 1014,
    slug: 'soy-protein-isolate',
    name: 'Soy Protein Isolate',
    description:
      'Defatted soy protein isolate with 90% protein content. Unflavoured, suitable for shakes, baking, and plant-based recipe fortification.',
    category: 'Sports Nutrition',
    mixingGroup: 'food-grade',
    consumptionClassification: 'food',
    imageSetId: 'soy-protein-isolate',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Pale beige',
      source: 'Defatted soy beans, water-extracted and dried',
      intendedUse: 'Plant-based protein supplement for shakes and cooking',
      storage: 'Store in a cool dry place. Reseal after opening.',
      consumptionClassification: 'food',
    },
    categoryFacts: {
      ...({
        texture: 'Fine powder',
        colour: 'Pale beige',
        source: 'Defatted soy beans, water-extracted and dried',
        intendedUse: 'Plant-based protein supplement for shakes and cooking',
        storage: 'Store in a cool dry place. Reseal after opening.',
        consumptionClassification: 'food',
      } as const),
      flavour: 'Unflavoured',
      servings: 33,
      proteinPerServing: 27,
      carbsPerServing: 0,
      ingredients: ['Soy protein isolate'],
      allergens: ['Soy'],
      nutrition: { energy: '115 kcal', protein: '27 g', carbohydrate: '0 g', fat: '1 g' },
      servingSize: '30 g',
      dietaryAttributes: ['Vegan', 'Gluten-free', 'Dairy-free'],
    },
    tags: ['soy', 'protein', 'plant-based', 'vegan', 'unflavoured'],
    createdAt: '2025-03-05T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('SPN-1014-001', '500 g Bag', 500, 2195, 30, 1),
      makeVariant('SPN-1014-002', '1 kg Bag', 1000, 3695, 20, 2),
      makeVariant('SPN-1014-003', '2.5 kg Bag', 2500, 7995, 10, 3),
    ],
  },
]);
