import { industrializeProducts, type CatalogProduct, makeVariant } from '../model.js';

export const tradeCreativeProducts: readonly CatalogProduct[] = industrializeProducts([
  {
    id: 33,
    slug: 'portland-cement',
    name: 'Portland Cement',
    description:
      'General-purpose Portland cement (CEM I 42.5N) for concrete, mortar, render, and general construction. Fine grey powder that hardens when mixed with water and aggregate.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'cementitious-materials',
    consumptionClassification: 'caution',
    imageSetId: 'portland-cement',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Grey',
      source: 'Calcined limestone and clay, ground with gypsum',
      intendedUse: 'Concrete production, mortar, render, screed, and general building',
      storage:
        'Store in a dry place off the ground. Use within 3 months for best strength. Keep sealed to prevent moisture ingress.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Grey',
      source: 'Calcined limestone and clay, ground with gypsum',
      intendedUse: 'Concrete production, mortar, render, screed, and general building',
      storage:
        'Store in a dry place off the ground. Use within 3 months for best strength. Keep sealed to prevent moisture ingress.',
      consumptionClassification: 'caution',
      composition: 'Portland cement clinker (95%), gypsum (5%)',
      waterRatio: 'Approximately 0.4 litre water per 1 kg cement for standard mortar',
      coverage:
        'One 25 kg bag produces approximately 0.013 m3 of concrete when mixed with aggregate',
      settingTime: 'Initial set: 45-60 minutes at 20 C. Final set: 6-10 hours.',
      ppe: [
        'Dust mask (P2/P3)',
        'Safety glasses',
        'Protective gloves',
        'Long sleeves and trousers',
      ],
    },
    tags: ['cement', 'portland', 'construction', 'concrete'],
    createdAt: '2025-02-02T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0033-001', '5 kg Bag', 5000, 495, 45, 1),
      makeVariant('TCM-0033-002', '25 kg Bag', 25000, 1595, 30, 2),
    ],
  },
  {
    id: 34,
    slug: 'plaster-of-paris',
    name: 'Plaster of Paris',
    description:
      'Fine hemihydrate plaster powder for casting, moulding, craft, and small repairs. Sets to a hard white surface within 20-30 minutes when mixed with water.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'casting-materials',
    consumptionClassification: 'caution',
    imageSetId: 'plaster-of-paris',
    baseFacts: {
      texture: 'Very fine powder',
      colour: 'White',
      source: 'Calcined gypsum (calcium sulfate hemihydrate)',
      intendedUse: 'Casting, mould-making, craft projects, and small plaster repairs',
      storage:
        'Store in a completely dry place. Product hardens irreversibly on contact with moisture.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Very fine powder',
      colour: 'White',
      source: 'Calcined gypsum (calcium sulfate hemihydrate)',
      intendedUse: 'Casting, mould-making, craft projects, and small plaster repairs',
      storage:
        'Store in a completely dry place. Product hardens irreversibly on contact with moisture.',
      consumptionClassification: 'caution',
      composition: 'Calcium sulfate hemihydrate (CaSO4-0.5H2O) > 95%',
      waterRatio: '2 parts plaster to 1 part water by weight',
      coverage: 'One 1 kg bag produces approximately 0.8 litres of mixed plaster',
      settingTime: 'Working time: 5-10 minutes. Initial set: 20-30 minutes. Full cure: 24 hours.',
      ppe: ['Dust mask', 'Safety glasses', 'Gloves recommended for prolonged contact'],
    },
    tags: ['plaster', 'casting', 'craft', 'moulding'],
    createdAt: '2025-02-03T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0034-001', '1 kg Bag', 1000, 495, 50, 1),
      makeVariant('TCM-0034-002', '5 kg Bag', 5000, 1495, 30, 2),
      makeVariant('TCM-0034-003', '25 kg Bag', 25000, 4995, 15, 3),
    ],
  },
  {
    id: 35,
    slug: 'tile-grout',
    name: 'Tile Grout',
    description:
      'Cement-based tile grouting powder in natural grey. Suitable for wall and floor tile joints up to 6 mm width in kitchens, bathrooms, and wet areas.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'cementitious-materials',
    consumptionClassification: 'caution',
    imageSetId: 'tile-grout',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Grey',
      source: 'Portland cement, fine silica sand, polymers, pigments',
      intendedUse: 'Filling joints between ceramic and porcelain tiles',
      storage: 'Store in a dry place. Use within 6 months of opening. Keep sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Grey',
      source: 'Portland cement, fine silica sand, polymers, pigments',
      intendedUse: 'Filling joints between ceramic and porcelain tiles',
      storage: 'Store in a dry place. Use within 6 months of opening. Keep sealed.',
      consumptionClassification: 'caution',
      composition:
        'White Portland cement, graded silica sand, polymer modifiers, water-retention agents',
      waterRatio: 'Approximately 0.3 litre water per 1 kg grout powder',
      coverage:
        'One 2.5 kg bag grouts approximately 10-15 m2 of standard tiles depending on joint width',
      settingTime: 'Working time: 20-30 minutes. Walkable after 24 hours. Full cure: 7 days.',
      ppe: ['Dust mask', 'Protective gloves', 'Safety glasses'],
    },
    tags: ['grout', 'tile', 'flooring', 'cement-based'],
    createdAt: '2025-02-04T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0035-001', '2.5 kg Bag', 2500, 745, 40, 1),
      makeVariant('TCM-0035-002', '10 kg Bag', 10000, 2195, 25, 2),
    ],
  },
  {
    id: 36,
    slug: 'dry-pigment-titanium-white',
    name: 'Dry Pigment - Titanium White',
    description:
      'High-opacity titanium dioxide pigment powder for use in paints, plasters, concrete, and artist materials. Excellent lightfastness and tinting strength.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'pigments',
    consumptionClassification: 'caution',
    imageSetId: 'dry-pigment-titanium-white',
    baseFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Bright white',
      source: 'Synthetic titanium dioxide (rutile), surface-treated',
      intendedUse: 'Universal white pigment for paints, coatings, plasters, and craft',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Ultra-fine powder',
      colour: 'Bright white',
      source: 'Synthetic titanium dioxide (rutile), surface-treated',
      intendedUse: 'Universal white pigment for paints, coatings, plasters, and craft',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'caution',
      composition: 'Titanium dioxide (TiO2) > 93%, alumina and silica coating',
      waterRatio: 'Dispersible in water and oil-based binders. No fixed ratio.',
      coverage:
        'One 500 g tints approximately 10-25 kg of plaster or paint depending on desired opacity',
      settingTime: 'Does not set independently. Curing depends on binder used.',
      ppe: ['Dust mask (P2)', 'Safety glasses', 'Gloves', 'Avoid generating airborne dust'],
    },
    tags: ['pigment', 'white', 'titanium-dioxide', 'paint'],
    createdAt: '2025-02-05T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('TCM-0036-001', '250 g Jar', 250, 895, 35, 1, { compareAtPriceCents: 1095 }),
      makeVariant('TCM-0036-002', '1 kg Jar', 1000, 2495, 20, 2),
    ],
  },
  {
    id: 37,
    slug: 'dry-pigment-iron-oxide-red',
    name: 'Dry Pigment - Iron Oxide Red',
    description:
      'Synthetic iron oxide red pigment powder for colouring concrete, plaster, paint, and craft materials. UV-stable and alkali-resistant with consistent warm tone.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'pigments',
    consumptionClassification: 'caution',
    imageSetId: 'dry-pigment-iron-oxide-red',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Deep brick red',
      source: 'Synthetic iron oxide (Fe2O3), precipitated',
      intendedUse: 'Colouring concrete, render, plaster, and artist materials',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Deep brick red',
      source: 'Synthetic iron oxide (Fe2O3), precipitated',
      intendedUse: 'Colouring concrete, render, plaster, and artist materials',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'caution',
      composition: 'Synthetic iron oxide red (Fe2O3) > 95%',
      waterRatio: 'Mix thoroughly into dry binder before adding water for best dispersion',
      coverage: 'One 250 g tints approximately 25 kg of dry cement to a medium red shade',
      settingTime: 'Does not set independently. No effect on binder setting time.',
      ppe: ['Dust mask', 'Gloves', 'Safety glasses', 'Avoid generating dust clouds'],
    },
    tags: ['pigment', 'red', 'iron-oxide', 'concrete-colour'],
    createdAt: '2025-02-06T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0037-001', '250 g Jar', 250, 745, 30, 1),
      makeVariant('TCM-0037-002', '1 kg Jar', 1000, 2195, 18, 2),
    ],
  },
  {
    id: 38,
    slug: 'dry-pigment-ultramarine-blue',
    name: 'Dry Pigment - Ultramarine Blue',
    description:
      'Synthetic ultramarine blue pigment powder for bright blue colouration in plasters, renders, artists paints, and craft projects. Good lightfastness and alkali resistance.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'pigments',
    consumptionClassification: 'caution',
    imageSetId: 'dry-pigment-ultramarine-blue',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Vibrant blue',
      source: 'Synthetic sodium aluminium sulfosilicate',
      intendedUse: 'Blue pigment for decorative plaster, paint, and artist media',
      storage: 'Store in a cool dry place. Protect from prolonged exposure to light.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Vibrant blue',
      source: 'Synthetic sodium aluminium sulfosilicate',
      intendedUse: 'Blue pigment for decorative plaster, paint, and artist media',
      storage: 'Store in a cool dry place. Protect from prolonged exposure to light.',
      consumptionClassification: 'caution',
      composition: 'Synthetic ultramarine (Na7Al6Si6O24S3) > 97%',
      waterRatio: 'Disperse in a small amount of water before adding to binder for even colour',
      coverage: 'One 250 g tints approximately 25 kg of dry cement to a medium blue shade',
      settingTime: 'Does not set independently. Stable in cementitious and lime binders.',
      ppe: ['Dust mask', 'Gloves', 'Safety glasses'],
    },
    tags: ['pigment', 'blue', 'ultramarine', 'art-material'],
    createdAt: '2025-02-07T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0038-001', '250 g Jar', 250, 845, 25, 1),
      makeVariant('TCM-0038-002', '1 kg Jar', 1000, 2495, 15, 2),
    ],
  },
  {
    id: 46,
    slug: 'ready-mix-mortar',
    name: 'Ready-Mix Mortar',
    description:
      'Pre-blended mortar powder of cement, lime, and graded sand for bricklaying, block work, and pointing. Just add water for consistent workable mortar on site.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'cementitious-materials',
    consumptionClassification: 'caution',
    imageSetId: 'ready-mix-mortar',
    baseFacts: {
      texture: 'Coarse-fine granular mix',
      colour: 'Grey',
      source: 'Portland cement, hydrated lime, washed sharp sand',
      intendedUse: 'Bricklaying, blocklaying, repointing, and general masonry repairs',
      storage: 'Store in a dry place on a raised surface. Protect from rain and ground moisture.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Coarse-fine granular mix',
      colour: 'Grey',
      source: 'Portland cement, hydrated lime, washed sharp sand',
      intendedUse: 'Bricklaying, blocklaying, repointing, and general masonry repairs',
      storage: 'Store in a dry place on a raised surface. Protect from rain and ground moisture.',
      consumptionClassification: 'caution',
      composition: 'Portland cement, hydrated lime, graded sharp sand (1:1:6 ratio)',
      waterRatio: 'Approximately 0.16 litre water per 1 kg of dry mortar mix',
      coverage: 'One 25 kg bag lays approximately 25-30 standard bricks with 10 mm joints',
      settingTime:
        'Working time: 1-2 hours at 20 C. Initial set: 3-5 hours. Full strength: 28 days.',
      ppe: ['Dust mask', 'Protective gloves', 'Safety glasses', 'Knee pads for bricklaying'],
    },
    tags: ['mortar', 'bricklaying', 'masonry', 'ready-mix'],
    createdAt: '2025-02-15T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0046-001', '5 kg Bag', 5000, 495, 40, 1),
      makeVariant('TCM-0046-002', '25 kg Bag', 25000, 1495, 28, 2),
    ],
  },
  {
    id: 47,
    slug: 'casting-resin-powder',
    name: 'Casting Resin Powder',
    description:
      'Two-part polyurethane casting resin in separate powder components. Mix parts A and B to create a low-viscosity casting resin for jewellery, models, and prototypes.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'casting-materials',
    consumptionClassification: 'caution',
    imageSetId: 'casting-resin-powder',
    baseFacts: {
      texture: 'Fine powder and granular powder (two sachets)',
      colour: 'White (Part A) and off-white (Part B)',
      source: 'Polyol powder (A) and isocyanate powder (B), formulated for room-temperature cure',
      intendedUse: 'Casting small objects, prototypes, jewellery, and decorative pieces',
      storage: 'Store in a cool dry place. Keep sachets sealed until use. Protect from moisture.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder and granular powder (two sachets)',
      colour: 'White (Part A) and off-white (Part B)',
      source: 'Polyol powder (A) and isocyanate powder (B), formulated for room-temperature cure',
      intendedUse: 'Casting small objects, prototypes, jewellery, and decorative pieces',
      storage: 'Store in a cool dry place. Keep sachets sealed until use. Protect from moisture.',
      consumptionClassification: 'caution',
      composition:
        'Part A: Polyether polyol. Part B: Modified MDI isocyanate. Mix ratio 1:1 by weight.',
      waterRatio: 'Do not add water. Moisture inhibits cure and causes foaming.',
      coverage: 'One 500 g kit produces approximately 450 ml of cured resin',
      settingTime: 'Pot life: 3-5 minutes. Demould time: 15-30 minutes. Full cure: 24 hours.',
      ppe: [
        'Nitrile gloves',
        'Safety glasses',
        'Vapour respirator (organic vapour)',
        'Work in well-ventilated area',
      ],
    },
    tags: ['resin', 'casting', 'polyurethane', 'moulding'],
    createdAt: '2025-02-16T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0047-001', '500 g Kit', 500, 2195, 22, 1),
      makeVariant('TCM-0047-002', '1 kg Kit', 1000, 3795, 14, 2),
    ],
  },
  {
    id: 48,
    slug: 'stone-dust',
    name: 'Stone Dust',
    description:
      'Fine granite stone dust, also known as quarry dust or crusher fines. Used as a bedding layer for paving, a filler in concrete, and for hard landscaping projects.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'cementitious-materials',
    consumptionClassification: 'non-food',
    imageSetId: 'stone-dust',
    baseFacts: {
      texture: 'Fine gritty powder',
      colour: 'Grey',
      source: 'Crushed granite screening, washed and graded',
      intendedUse: 'Paving bedding, concrete filler, path base, and landscaping',
      storage: 'Store in a dry place. Cover to protect from rain.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine gritty powder',
      colour: 'Grey',
      source: 'Crushed granite screening, washed and graded',
      intendedUse: 'Paving bedding, concrete filler, path base, and landscaping',
      storage: 'Store in a dry place. Cover to protect from rain.',
      consumptionClassification: 'non-food',
      composition:
        'Crushed granite aggregate, particle size 0-5 mm, containing quartz, feldspar, and mica',
      waterRatio: 'Add water sparingly until just damp for paving bedding. Do not saturate.',
      coverage: 'One 25 kg bag covers approximately 1 m2 at 25 mm depth',
      settingTime: 'Does not set. Compacts mechanically and remains granular.',
      ppe: [
        'Dust mask',
        'Safety glasses',
        'Gloves',
        'Avoid breathing respirable crystalline silica dust',
      ],
    },
    tags: ['stone-dust', 'quarry', 'paving', 'aggregate'],
    createdAt: '2025-02-17T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0048-001', '15 kg Bag', 15000, 745, 35, 1),
      makeVariant('TCM-0048-002', '25 kg Bag', 25000, 1095, 25, 2),
    ],
  },
  {
    id: 49,
    slug: 'bentonite-clay',
    name: 'Bentonite Clay',
    description:
      'Sodium bentonite clay powder with high swelling capacity. Used for pond sealing, drilling mud, foundry sand binding, ceramic bodies, and environmental barrier applications.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'absorbents',
    consumptionClassification: 'non-food',
    imageSetId: 'bentonite-clay',
    baseFacts: {
      texture: 'Very fine soft powder',
      colour: 'Grey to pale green-grey',
      source: 'Mined and milled sodium montmorillonite clay',
      intendedUse: 'Pond sealing, foundry binder, drilling fluid, ceramics, and spill absorbent',
      storage: 'Store in a dry place. Product absorbs significant moisture when exposed to air.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Very fine soft powder',
      colour: 'Grey to pale green-grey',
      source: 'Mined and milled sodium montmorillonite clay',
      intendedUse: 'Pond sealing, foundry binder, drilling fluid, ceramics, and spill absorbent',
      storage: 'Store in a dry place. Product absorbs significant moisture when exposed to air.',
      consumptionClassification: 'non-food',
      composition: 'Sodium montmorillonite > 85%, minor quartz and feldspar',
      waterRatio:
        'Absorbs up to 5 times its weight in water. Add powder to water, not water to powder.',
      coverage:
        'One 25 kg bag seals approximately 5 m2 of pond base at 5 kg per m2 application rate',
      settingTime:
        'Hydrates in minutes. Forms a gel barrier that self-heals when punctured. Does not chemically set.',
      ppe: ['Dust mask', 'Safety glasses', 'Gloves', 'Wet product is extremely slippery'],
    },
    tags: ['bentonite', 'clay', 'sealing', 'absorbent'],
    createdAt: '2025-02-18T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0049-001', '5 kg Bag', 5000, 895, 30, 1),
      makeVariant('TCM-0049-002', '25 kg Bag', 25000, 2995, 18, 2),
    ],
  },
  {
    id: 50,
    slug: 'silica-sand',
    name: 'Silica Sand',
    description:
      'High-purity silica sand powder with consistent 0.1-0.5 mm grain size. For foundry moulding, sandblasting, glass making, water filtration, and construction mixes.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'cementitious-materials',
    consumptionClassification: 'caution',
    imageSetId: 'silica-sand',
    baseFacts: {
      texture: 'Fine gritty granular powder',
      colour: 'White to pale cream',
      source: 'Washed and graded natural silica sand from quarry',
      intendedUse: 'Foundry sand, sandblasting, glass batch, filtration media, mortar aggregate',
      storage: 'Store in a dry place. Keep covered and away from contaminants.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine gritty granular powder',
      colour: 'White to pale cream',
      source: 'Washed and graded natural silica sand from quarry',
      intendedUse: 'Foundry sand, sandblasting, glass batch, filtration media, mortar aggregate',
      storage: 'Store in a dry place. Keep covered and away from contaminants.',
      consumptionClassification: 'caution',
      composition: 'Silicon dioxide (SiO2) > 99%, trace iron oxide and alumina',
      waterRatio:
        'Used dry for sandblasting and foundry. For mortar, mix 3 parts sand to 1 part cement.',
      coverage: 'One 25 kg bag fills approximately 15 litres volume',
      settingTime: 'Does not set. Inert filler; setting depends on binder used.',
      ppe: [
        'P3 respirator for sandblasting',
        'Safety glasses',
        'Gloves',
        'Respirable crystalline silica dust hazard: avoid breathing dust',
      ],
    },
    tags: ['silica', 'sand', 'foundry', 'filtration'],
    createdAt: '2025-02-19T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0050-001', '10 kg Bag', 10000, 845, 40, 1),
      makeVariant('TCM-0050-002', '25 kg Bag', 25000, 1695, 25, 2),
    ],
  },
  {
    id: 39,
    slug: 'hydrated-lime',
    name: 'Hydrated Lime',
    description:
      'Builders hydrated lime powder (calcium hydroxide) for mortar plasticising, lime wash, soil stabilisation, and traditional plaster and render mixes.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'cementitious-materials',
    consumptionClassification: 'caution',
    imageSetId: 'hydrated-lime',
    baseFacts: {
      texture: 'Very fine soft powder',
      colour: 'White',
      source: 'Calcium oxide slaked with water, dried and ground',
      intendedUse: 'Mortar additive, lime wash, soil treatment, and traditional building',
      storage:
        'Store in completely dry conditions. Product reacts with atmospheric CO2 and moisture.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Very fine soft powder',
      colour: 'White',
      source: 'Calcium oxide slaked with water, dried and ground',
      intendedUse: 'Mortar additive, lime wash, soil treatment, and traditional building',
      storage:
        'Store in completely dry conditions. Product reacts with atmospheric CO2 and moisture.',
      consumptionClassification: 'caution',
      composition: 'Calcium hydroxide Ca(OH)2 > 93%',
      waterRatio:
        'For lime wash: 1 kg lime to 2-3 litres water. For mortar: replaces 1 part cement.',
      coverage:
        'One 25 kg bag treats approximately 500 m2 of acidic soil or produces 50 litres of lime wash',
      settingTime: 'Carbonation cure over weeks to months depending on thickness and humidity',
      ppe: [
        'Dust mask (P2)',
        'Chemical-resistant gloves',
        'Safety glasses',
        'Long clothing. Lime burns on wet skin.',
      ],
    },
    tags: ['lime', 'mortar', 'lime-wash', 'alkaline'],
    createdAt: '2025-02-08T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-0039-001', '5 kg Bag', 5000, 795, 35, 1),
      makeVariant('TCM-0039-002', '25 kg Bag', 25000, 2495, 20, 2),
    ],
  },
  {
    id: 40,
    slug: 'dry-pigment-yellow-ochre',
    name: 'Dry Pigment - Yellow Ochre',
    description:
      'Natural yellow ochre pigment powder from iron-rich clay. Warm earthy yellow with excellent UV and alkali stability for plasters, paints, and craft use.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'pigments',
    consumptionClassification: 'caution',
    imageSetId: 'dry-pigment-yellow-ochre',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Warm earthy yellow',
      source: 'Natural iron oxide clay (limonite), washed and ground',
      intendedUse: 'Warm-toned pigment for plaster, paint, and artist materials',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Warm earthy yellow',
      source: 'Natural iron oxide clay (limonite), washed and ground',
      intendedUse: 'Warm-toned pigment for plaster, paint, and artist materials',
      storage: 'Store in a cool dry place. Keep container sealed.',
      consumptionClassification: 'caution',
      composition: 'Natural hydrated iron oxide (FeO(OH)-nH2O) with clay and silica > 95%',
      waterRatio: 'Mix with small amount of water to a paste before adding to binder',
      coverage: 'One 250 g tints approximately 25 kg of dry plaster to a warm ochre tone',
      settingTime: 'Does not set independently. Inert in all common binders.',
      ppe: ['Dust mask', 'Gloves', 'Safety glasses'],
    },
    tags: ['pigment', 'yellow-ochre', 'natural', 'earth-colour'],
    createdAt: '2025-02-09T00:00:00.000Z',
    visibility: 'public',
    onSale: true,
    variants: [
      makeVariant('TCM-0040-001', '250 g Jar', 250, 695, 28, 1, { compareAtPriceCents: 845 }),
      makeVariant('TCM-0040-002', '1 kg Jar', 1000, 1995, 18, 2),
    ],
  },
  {
    id: 1049,
    slug: 'rapid-set-cement',
    name: 'Rapid-Set Cement',
    description:
      'Fast-setting hydraulic cement for quick repairs to steps, paths, posts, and fixtures. Sets in 10-15 minutes and reaches service strength within 2 hours.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'cementitious-materials',
    consumptionClassification: 'caution',
    imageSetId: 'rapid-set-cement',
    baseFacts: {
      texture: 'Fine powder',
      colour: 'Light grey',
      source: 'Calcium sulfoaluminate cement, finely ground',
      intendedUse: 'Rapid repairs to concrete, posts, steps, and anchoring fixtures',
      storage: 'Store in a completely dry place. Product hardens quickly on contact with moisture.',
      consumptionClassification: 'caution',
    },
    categoryFacts: {
      texture: 'Fine powder',
      colour: 'Light grey',
      source: 'Calcium sulfoaluminate cement, finely ground',
      intendedUse: 'Rapid repairs to concrete, posts, steps, and anchoring fixtures',
      storage: 'Store in a completely dry place. Product hardens quickly on contact with moisture.',
      consumptionClassification: 'caution',
      composition: 'Calcium sulfoaluminate clinker, anhydrite, minor additives',
      waterRatio: '0.18-0.22 litre water per 1 kg of powder',
      coverage: 'One 5 kg bag repairs approximately 0.003 m3 of concrete',
      settingTime:
        'Working time: 5 minutes. Initial set: 10-15 minutes. Service strength: 2 hours.',
      ppe: ['Dust mask', 'Safety glasses', 'Gloves', 'Work quickly: short working time'],
    },
    tags: ['cement', 'rapid-set', 'repair', 'fast-cure'],
    createdAt: '2025-04-09T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-1049-001', '5 kg Tub', 5000, 1195, 30, 1),
      makeVariant('TCM-1049-002', '15 kg Tub', 15000, 2895, 18, 2),
    ],
  },
  {
    id: 1050,
    slug: 'wood-filler-powder',
    name: 'Wood Filler Powder',
    description:
      'Cellulose-based wood filler powder for mixing with water to repair cracks, holes, and gouges in interior wood. Sands smooth and accepts paint or stain.',
    category: 'Trade & Creative Materials',
    mixingGroup: 'casting-materials',
    consumptionClassification: 'non-food',
    imageSetId: 'wood-filler-powder',
    baseFacts: {
      texture: 'Fine fibrous powder',
      colour: 'Natural wood tone (light beige)',
      source: 'Wood cellulose fibre, binders, mineral fillers',
      intendedUse: 'Repairing cracks, nail holes, and surface defects in interior wood',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'non-food',
    },
    categoryFacts: {
      texture: 'Fine fibrous powder',
      colour: 'Natural wood tone (light beige)',
      source: 'Wood cellulose fibre, binders, mineral fillers',
      intendedUse: 'Repairing cracks, nail holes, and surface defects in interior wood',
      storage: 'Store in a cool dry place. Keep container tightly sealed.',
      consumptionClassification: 'non-food',
      composition: 'Cellulose wood fibre, calcium carbonate, PVA binder, pigments',
      waterRatio: 'Mix 3 parts powder to 1 part water to form a stiff paste',
      coverage: 'One 250 g tub fills approximately 200 ml of void volume',
      settingTime: 'Working time: 10 minutes. Sandable after 30 minutes. Full hardness: 24 hours.',
      ppe: ['Dust mask when sanding', 'Gloves recommended'],
    },
    tags: ['wood-filler', 'repair', 'cellulose', 'decorating'],
    createdAt: '2025-04-10T00:00:00.000Z',
    visibility: 'public',
    onSale: false,
    variants: [
      makeVariant('TCM-1050-001', '250 g Tub', 250, 595, 38, 1),
      makeVariant('TCM-1050-002', '1 kg Tub', 1000, 1495, 25, 2),
    ],
  },
]);
